production: 
  class: \Klikasi\Model\Aurkezpena
  fields: 
    edukiaId: 
      title: _('Edukia id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Edukia
          fieldName: 
            fields: 
              - titulua
            template: '%titulua%'
          order: titulua
      default: true
    titulua: 
      title: _('Titulua')
      type: text
      maxLength: 350
    url: 
      title: _('Url')
      type: text
      maxLength: 750
    klikKopurua: 
      title: _('Klik kopurua')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    mota: 
      title: _('Mota')
      type: select
      defaultValue: slideshare
      source: 
        data: inline
        values: 
          'slideshare': _('slideshare')
          'issuu': _('issuu')
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
