production: 
  class: \Klikasi\Model\IkastegiMota
  fields: 
    izena: 
      title: _('Izena')
      type: text
      required: true
      maxLength: 250
      default: true
    url: 
      title: _('Url')
      type: text
      required: true
      maxLength: 350
    default: 
      title: _('Default')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
