production: 
  class: \Klikasi\Model\Iruzkina
  fields: 
    iruzkinaId: 
      title: _('Iruzkina id')
      type: select
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Iruzkina
          fieldName: 
            fields: 
              - egoera
            template: '%egoera%'
          order: egoera
        'null': _("Unasigned")
      default: true
    edukiaId: 
      title: _('Edukia id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Edukia
          fieldName: 
            fields: 
              - titulua
            template: '%titulua%'
          order: titulua
    erabiltzaileaId: 
      title: _('Erabiltzailea id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    iruzkin: 
      title: _('Iruzkin')
      type: textarea
      required: true
    egoera: 
      title: _('Egoera')
      type: select
      defaultValue: onartzeko
      source: 
        data: inline
        values: 
          'onartzeko': _('onartzeko')
          'onartua': _('onartua')
          'ezOnartua': _('ezOnartua')
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
