production: 
  class: \Klikasi\Model\Jakinarazpenak
  fields: 
    erabiltzaileaId: 
      title: _('Erabiltzailea id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
    idKanpotarra: 
      title: _('Id kanpotarra')
      type: number
      required: true
      source: 
        control: Spinner
    ikusita: 
      title: _('Ikusita')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    message: 
      title: _('Message')
      type: textarea
    postazJakinarazi: 
      title: _('Postaz jakinarazi')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    thatUserId: 
      title: _('That user id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    motaId: 
      title: _('Mota id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\JakinarazpenakMota
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    deletedBySender: 
      title: _('Deleted by sender')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    deletedByErabiltzailea: 
      title: _('Deleted by erabiltzailea')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    egoera: 
      title: _('Egoera')
      type: select
      defaultValue: onartzeko
      source: 
        data: inline
        values: 
          'onartzeko': _('onartzeko')
          'onartua': _('onartua')
          'ezOnartua': _('ezOnartua')
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
