production: 
  class: \Klikasi\Model\Mezuak
  fields: 
    norkId: 
      title: _('Nork id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
    noriId: 
      title: _('Nori id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    mezua: 
      title: _('Mezua')
      type: textarea
      required: true
    mota: 
      title: _('Mota')
      type: select
      required: true
      source: 
        data: inline
        values: 
          'iradokizuna': _('iradokizuna')
          'mezua': _('mezua')
          'moderazioa': _('moderazioa')
          'edukia': _('edukia')
    ikusita: 
      title: _('Ikusita')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': _('0')
          '1': _('1')
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    edukiaId: 
      title: _('Edukia id')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
