production: 
  class: \Klikasi\Model\Notifikazioa
  fields: 
    titulua: 
      title: _('Titulua')
      type: text
      required: true
      maxLength: 350
      default: true
    edukiaHtml: 
      title: _('Edukia html')
      type: textarea
      required: true
      source: 
        control: tinymce
        template: simple
    edukiaText: 
      title: _('Edukia text')
      type: textarea
      required: true
    identifikatzailea: 
      title: _('Identifikatzailea')
      type: text
      required: true
      maxLength: 350
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
