<?php
$ikastegia = $this->ikastegia;

$edukiakOnartua = $ikastegia->edukiakOnartua();
$edukiakOnartzeko = $ikastegia->edukiakOnartzeko();

$mapper = new \Klikasi\Mapper\Sql\Erabiltzailea();
$user = $mapper->find(18);
?>
<div id="nire-edukiak">

    <div class="form-group">
        <h2><?php echo $this->translate('[es] Recursos Actuales'); ?></h2>

        <div class="col-xs-12" id="nireEdukiakOnartua">
            <?php
            $noMoreNireEdukiak = true;
            if (!empty($edukiakOnartua)) {
                $noMoreNireEdukiak = false;
                foreach ($edukiakOnartua as $edukia) {
                    $erabiltzailea = $edukia->getErabiltzailea();
                ?>
                <div class="row notificationCustomRow" data-relation="<?php echo $edukia->getId(); ?>">

                    <div class="row">
                        <div class="col-xs-6 col-sm-6 pull-left">
                            <a
                                href="<?php echo $this->baseUrl('edukiak/ikusi/edukia/' .$edukia->getUrl()); ?>"
                                title="<?php echo $edukia->getTitulua(); ?>"
                                ><?php echo $edukia->getTitulua(); ?></a> <small><?php echo $edukia->kategoriaFirst()->getIzena(); ?></small>
                        </div>
                        <div class="col-xs-6 col-sm-6 pull-right text-right">
                            <small><?php echo $edukia->getSortzeData(); ?></small>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12">
                            <p><?php echo $edukia->getDeskribapenLaburra(); ?></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-6 col-sm-6 pull-left">
                            <a
                                href="<?php echo $this->baseUrl('erabiltzaileak/ikusi/erabiltzailea/' . $erabiltzailea->getUrl()); ?>"
                                title="<?php echo $erabiltzailea->getCompletName(); ?>"
                                ><?php echo $this->ErabiltzaileIrudia($erabiltzailea, 22, true); ?> <?php echo $erabiltzailea->getCompletName(); ?></a>
                        </div>

                        <div class="col-xs-6 col-sm-6 pull-right text-right">
                            <button
                                data-action="unlinkEdukia"
                                data-relation="<?php echo $edukia->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Desvincular recurso'); ?>"
                                ><i class="fa fa-ban text-danger" style="position: static;"></i></button>
                        </div>
                    </div>

                </div>
                <?php
                }

            }
            ?>
            <div class="col-xs-12 noMoreNireEdukiak <?php echo (!$noMoreNireEdukiak ? 'hide' : '') ?>" >
                <p><?php echo $this->translate('[es] No hay recursos aceptados'); ?></p>
            </div>
        </div>
    </div>

    <div class="form-group">

        <h2><?php echo $this->translate('[es] Recursos Pendientes de Moderación'); ?></h2>

        <div class="col-xs-12" id="nireEdukiakOnartzeko">
            <?php
            $noMoreModerateEdukiak = true;
            if (!empty($edukiakOnartzeko)) {
                $noMoreModerateEdukiak = false;
                foreach ($edukiakOnartzeko as $edukia) {
                    $erabiltzailea = $edukia->getErabiltzailea();
                    ?>
                    <div class="row notificationCustomRow" data-relation="<?php echo $edukia->getId(); ?>">

                    <div class="row">
                        <div class="col-xs-6 col-sm-6 pull-left">
                            <a
                                href="<?php echo $this->baseUrl('edukiak/ikusi/edukia/' .$edukia->getUrl()); ?>"
                                title="<?php echo $edukia->getTitulua(); ?>"
                                ><?php echo $edukia->getTitulua(); ?></a> <small><?php echo $edukia->kategoriaFirst()->getIzena(); ?></small>
                        </div>
                        <div class="col-xs-6 col-sm-6 pull-right text-right">
                            <small><?php echo $edukia->getSortzeData(); ?></small>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12">
                            <p><?php echo $edukia->getDeskribapenLaburra(); ?></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-6 col-sm-6 pull-left">
                            <a
                                href="<?php echo $this->baseUrl('erabiltzaileak/ikusi/erabiltzailea/' . $erabiltzailea->getUrl()); ?>"
                                title="<?php echo $erabiltzailea->getCompletName(); ?>"
                                ><?php echo $this->ErabiltzaileIrudia($erabiltzailea, 22, true); ?> <?php echo $erabiltzailea->getCompletName(); ?></a>
                        </div>

                        <div class="col-xs-6 col-sm-6 pull-right text-right">

                            <button
                                data-action="acceptEdukia"
                                data-relation="<?php echo $edukia->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Aceptar Recurso'); ?>"
                                ><i class="fa fa-thumbs-o-up" style="position: static;"></i></button>
                            <button
                                data-action="unlinkEdukia"
                                data-relation="<?php echo $edukia->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Rechazar Recurso'); ?>"
                                ><i class="fa fa-thumbs-o-down" style="position: static;"></i></button>

                        </div>
                    </div>

                </div>
                    <?php
                }
            }
            ?>
        </div>
        <div class="col-xs-12 noMoreModerateEdukiak <?php echo (!$noMoreModerateEdukiak ? 'hide' : '') ?>" >
            <p><?php echo $this->translate('[es] No hay recursos pendientes'); ?></p>
        </div>
    </div>
</div>