<?php
$ikastegia = $this->ikastegia;

$where = 'ikastegiaId = "' . $ikastegia->getId()  . '"'; // AND (administratzailea = 0 AND jabea = 0)';

$erabiltzaileaRelIkastegia = new \Klikasi\Mapper\Sql\ErabiltzaileaRelIkastegia();
$erabiltzaileaRelIkastegia = $erabiltzaileaRelIkastegia->fetchList($where);

?>

<div id="nire-ikaslea">
    <div class="form-group">
        <h2><?php echo $this->translate('[es] Estudiantes'); ?></h2>

        <div class="col-xs-12" id="nireIkaslea">
            <?php
            $noMoreIkaslea = true;
            if (!empty($erabiltzaileaRelIkastegia)) {
                $noMoreIkaslea = false;
                foreach ($erabiltzaileaRelIkastegia as $relIkaslea) {
                    $erabiltzailea = $relIkaslea->getErabiltzailea();
                    if ($erabiltzailea->getProfila() != "ikasle") {
                        continue;
                    }
                    ?>
                    <div class="row notificationCustomRow" data-relation="<?php echo $relIkaslea->getId(); ?>">

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 pull-left">
                                <a
                                    href="<?php echo $this->baseUrl('erabiltzaileak/ikusi/erabiltzailea/' . $erabiltzailea->getUrl()); ?>"
                                    title="<?php echo $erabiltzailea->getCompletName(); ?>"
                                    ><?php echo $this->ErabiltzaileIrudia($erabiltzailea, 22, true); ?> <?php echo $erabiltzailea->getCompletName(); ?></a>
                            </div>
                            <div class="col-xs-6 col-sm-6 pull-right text-right">
                                <p class="egoera"><?php echo $relIkaslea->getEgoera();?></p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12">
                                <p><?php echo $erabiltzailea->getDeskribapena(); ?></p>
                            </div>
                        </div>

                        <div class="row">

                            <div class="col-xs-6 col-sm-6 pull-left ikasleaModerationStatus"></div>

                            <div class="col-xs-6 col-sm-6 pull-right text-right">
                            <?php
                            $egoera = $relIkaslea->getEgoera();
                            $accept = false;
                            $reject = false;
                            if ($egoera == 'onartzeko') {
                                $accept = true;
                                $reject = true;
                            } elseif ($egoera == 'onartua') {
                                $reject = true;
                            } elseif ($egoera == 'ezOnartua') {
                                $accept = true;
                            }
                            ?>

                            <button
                                data-action="acceptIkaslea"
                                data-relation="<?php echo $relIkaslea->getId(); ?>"
                                class="btn btn-default <?php echo ($accept ? '' : 'hide');?>"
                                title="<?php echo $this->translate('[es] Aceptar Ikaslea'); ?>"
                                ><i class="fa fa-thumbs-o-up" style="position: static;"></i></button>
                            <button
                                data-action="rejectIkaslea"
                                data-relation="<?php echo $relIkaslea->getId(); ?>"
                                class="btn btn-default <?php echo ($reject ? '' : 'hide');?>"
                                title="<?php echo $this->translate('[es] Rechazar Ikaslea'); ?>"
                                ><i class="fa fa-thumbs-o-down" style="position: static;"></i></button>

                            </div>
                        </div>

                    </div>
                    <?php
                }
            }
            ?>
            <div class="col-xs-12 noMoreIkaslea <?php echo (!$noMoreIkaslea ? 'hide' : '') ?>" >
                <p><?php echo $this->translate('[es] No hay estudiantes'); ?></p>
            </div>
        </div>

    </div>
</div>