<?php
$ikastegia = $this->ikastegia;

$where = 'ikastegiaId = "' . $ikastegia->getId() . '"'; // AND (administratzailea = 1 OR jabea = 1)';

$erabiltzaileaRelIkastegia = new \Klikasi\Mapper\Sql\ErabiltzaileaRelIkastegia();
$erabiltzaileaRelIkastegia = $erabiltzaileaRelIkastegia->fetchList($where);
?>
<div id="nire-irakaslea">
    <div class="form-group">
        <h2><?php echo $this->translate('[es] Profesores'); ?></h2>

        <div class="col-xs-12" id="nireIrakaslea">
            <?php
            $noMoreIrakaslea = true;
            if (!empty($erabiltzaileaRelIkastegia)) {
                $noMoreIrakaslea = false;
                foreach ($erabiltzaileaRelIkastegia as $relIrakaslea) {
                    $erabiltzailea = $relIrakaslea->getErabiltzailea();
                    if ($erabiltzailea->getProfila() != "irakasle") {
                        continue;
                    }
                    ?>

                    <div class="row notificationCustomRow" data-relation="<?php echo $relIrakaslea->getId(); ?>">

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 pull-left">
                                <a
                                    href="<?php echo $this->baseUrl('erabiltzaileak/ikusi/erabiltzailea/' . $erabiltzailea->getUrl()); ?>"
                                    title="<?php echo $erabiltzailea->getCompletName(); ?>"
                                    ><?php echo $this->ErabiltzaileIrudia($erabiltzailea, 22, true); ?> <?php echo $erabiltzailea->getCompletName(); ?></a>
                            </div>
                            <div class="col-xs-6 col-sm-6 pull-right text-right">
                                <p class="egoera"><?php echo $relIrakaslea->getEgoera();?></p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12">
                                <p><?php echo $erabiltzailea->getDeskribapena(); ?></p>
                            </div>
                        </div>

                        <div class="row">

                            <div class="col-xs-6 col-sm-6 pull-left irakasleaModerationStatus"></div>

                            <div class="col-xs-6 col-sm-6 pull-right text-right">
                            <?php
                            $egoera = $relIrakaslea->getEgoera();
                            $accept = false;
                            $reject = false;
                            if ($egoera == 'onartzeko') {
                                $accept = true;
                                $reject = true;
                            } elseif ($egoera == 'onartua') {
                                $reject = true;
                            } elseif ($egoera == 'ezOnartua') {
                                $accept = true;
                            }
                            ?>

                            <button
                                data-action="acceptIrakaslea"
                                data-relation="<?php echo $relIrakaslea->getId(); ?>"
                                class="btn btn-default <?php echo ($accept ? '' : 'hide');?>"
                                title="<?php echo $this->translate('[es] Aceptar Irakaslea'); ?>"
                                ><i class="fa fa-thumbs-o-up" style="position: static;"></i></button>
                            <button
                                data-action="rejectIrakaslea"
                                data-relation="<?php echo $relIrakaslea->getId(); ?>"
                                class="btn btn-default <?php echo ($reject ? '' : 'hide');?>"
                                title="<?php echo $this->translate('[es] Rechazar Irakaslea'); ?>"
                                ><i class="fa fa-thumbs-o-down" style="position: static;"></i></button>

                            </div>
                        </div>

                    </div>
                    <?php
                }
            }
            ?>
            <div class="col-xs-12 noMoreIrakaslea <?php echo (!$noMoreIrakaslea ? 'hide' : '') ?>" >
                <p><?php echo $this->translate('[es] No hay profesores'); ?></p>
            </div>
        </div>
    </div>
</div>