#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedBideo
    fixedPositions:
      group:
        label: _("Datuak")
        colsPerRow: 4
        fields: 
          titulua: 2
          klikKopurua: 2
          url: 4

production: 
  main: 
    module: klearMatrix
    defaultScreen: bideoaList_screen
  screens: 
    bideoaList_screen: &bideoaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Bideoa
      title: _("List of %s", ngettext('Bideoa', 'Bideoa(s)', 0))
      fields: 
        blacklist:
          sortzeData: true
        options: 
          title: _("Options")
          screens: 
            bideoaEdit_screen: true
          dialogs: 
            bideoaDel_dialog: true
          default: bideoaEdit_screen
      options: 
        title: _("Options")
        screens: 
          bideoaNew_screen: true
        dialogs: 
            bideoaDel_dialog: true
    bideoaNew_screen: &bideoaNew_screenLink 
      <<: *Bideoa
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Bideoa', 'Bideoa(s)', 1))
      <<: *fixedBideo
      fields: 
        blacklist: 
          sortzeData: true
          klikKopurua: true
    bideoaEdit_screen: &bideoaEdit_screenLink 
      <<: *Bideoa
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Bideoa', 'Bideoa(s)', 1))
      <<: *fixedBideo
      fields: 
        blacklist: 
          sortzeData: true
        readOnly:
          klikKopurua: true
  dialogs: 
    bideoaDel_dialog: &bideoaDel_dialogLink 
      <<: *Bideoa
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Bideoa', 'Bideoa(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Bideoa', 'Bideoa(s)', 1))
      message: _("%s successfully deleted.", ngettext('Bideoa', 'Bideoa(s)', 1))
      labelOnList: true
      multiItem: true

testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
