#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: erabiltzaileaSettingsList_screen
  screens: 
    erabiltzaileaSettingsList_screen: &erabiltzaileaSettingsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *ErabiltzaileaSettings
      title: _("List of %s %2s", ngettext('Erabiltzailea setting', 'Erabiltzailea settings', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            erabiltzaileaSettingsEdit_screen: true
          dialogs: 
            erabiltzaileaSettingsDel_dialog: true
          default: erabiltzaileaSettingsEdit_screen
      options: 
        title: _("Options")
        screens: 
          erabiltzaileaSettingsNew_screen: true
        dialogs: 
          erabiltzaileaSettingsDel_dialog: true
    erabiltzaileaSettingsNew_screen: &erabiltzaileaSettingsNew_screenLink 
      <<: *ErabiltzaileaSettings
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Erabiltzailea setting', 'Erabiltzailea settings', 1))
      shortcutOption: N
    erabiltzaileaSettingsEdit_screen: &erabiltzaileaSettingsEdit_screenLink 
      <<: *ErabiltzaileaSettings
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Erabiltzailea setting', 'Erabiltzailea settings', 1), "[format| (%item%)]")
  dialogs: 
    erabiltzaileaSettingsDel_dialog: 
      <<: *ErabiltzaileaSettings
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Erabiltzailea setting', 'Erabiltzailea settings', 1))
      description: _("Do you want to delete this %s?", ngettext('Erabiltzailea setting', 'Erabiltzailea settings', 1))
      message: _("%s successfully deleted.", ngettext('Erabiltzailea setting', 'Erabiltzailea settings', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
