#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: etiketaList_screen
  screens: 
    etiketaList_screen: &etiketaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Etiketa
      title: _("List of %s", ngettext('Etiketa', 'Etiketa(s)', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            etiketaEdit_screen: true
          dialogs: 
            etiketaDel_dialog: true
          default: etiketaEdit_screen
      options: 
        title: _("Options")
        screens: 
          etiketaNew_screen: true
        dialogs: 
          etiketaDel_dialog: true
    etiketaNew_screen: &etiketaNew_screenLink 
      <<: *Etiketa
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Etiketa', 'Etiketa(s)', 1))
    etiketaEdit_screen: &etiketaEdit_screenLink 
      <<: *Etiketa
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Etiketa', 'Etiketa(s)', 1))
  dialogs: 
    etiketaDel_dialog: 
      <<: *Etiketa
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Etiketa', 'Etiketa(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Etiketa', 'Etiketa(s)', 1))
      message: _("%s successfully deleted.", ngettext('Etiketa', 'Etiketa(s)', 1))
      labelOnList: true
      multiItem: true

testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
