#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: hobekuntzakList_screen
  screens: 
    hobekuntzakList_screen: &hobekuntzakList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Hobekuntzak
      title: _("List of %s %2s", ngettext('Hobekuntzak', 'Hobekuntzak(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            hobekuntzakEdit_screen: true
          dialogs: 
            hobekuntzakDel_dialog: true
          default: hobekuntzakEdit_screen
      options: 
        title: _("Options")
        screens: 
          hobekuntzakNew_screen: true
        dialogs: 
          hobekuntzakDel_dialog: true
    hobekuntzakNew_screen: &hobekuntzakNew_screenLink 
      <<: *Hobekuntzak
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Hobekuntzak', 'Hobekuntzak(s)', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          sortzeData: true
    hobekuntzakEdit_screen: &hobekuntzakEdit_screenLink 
      <<: *Hobekuntzak
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Hobekuntzak', 'Hobekuntzak(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: 
    hobekuntzakDel_dialog: 
      <<: *Hobekuntzak
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Hobekuntzak', 'Hobekuntzak(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Hobekuntzak', 'Hobekuntzak(s)', 1))
      message: _("%s successfully deleted.", ngettext('Hobekuntzak', 'Hobekuntzak(s)', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
