#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: homePageList_screen
  screens: 
    homePageList_screen: &homePageList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *HomePage
      title: _("List of %s %2s", ngettext('Home page', 'Home page(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            homePageEdit_screen: true
          dialogs: 
            homePageDel_dialog: true
          default: homePageEdit_screen
      options: 
        title: _("Options")
        screens: 
          homePageNew_screen: true
        dialogs: 
          homePageDel_dialog: true
    homePageNew_screen: &homePageNew_screenLink 
      <<: *HomePage
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Home page', 'Home page(s)', 1))
      shortcutOption: N
    homePageEdit_screen: &homePageEdit_screenLink 
      <<: *HomePage
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Home page', 'Home page(s)', 1), "[format| (%item%)]")
  dialogs: 
    homePageDel_dialog: 
      <<: *HomePage
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Home page', 'Home page(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Home page', 'Home page(s)', 1))
      message: _("%s successfully deleted.", ngettext('Home page', 'Home page(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    IrudiaDownload_command: 
      <<: *HomePage
      controller: File
      action: force-download
      mainColumn: irudia
    IrudiaUpload_command: 
      <<: *HomePage
      controller: File
      action: upload
      mainColumn: irudia
    IrudiaPreview_command: 
      <<: *HomePage
      controller: File
      action: preview
      mainColumn: irudia
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
