#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: kategoriaList_screen
  screens: 
    kategoriaList_screen: &kategoriaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Kategoria
      title: _("List of %s", ngettext('Kategoria', 'Kategoria(s)', 0))
      fields:
        blacklist:
          url: true 
        options: 
          title: _("Options")
          screens: 
            kategoriaEdit_screen: true
          dialogs: 
            kategoriaDel_dialog: true
          default: kategoriaEdit_screen
      options: 
        title: _("Options")
        dialogs: 
          kategoriaDel_dialog: true
    kategoriaEdit_screen: &kategoriaEdit_screenLink 
      <<: *Kategoria
      controller: edit
      class: ui-silk-pencil
      label: false
      fields:
        readOnly:
          url: true
      title: _("Edit %s", ngettext('Kategoria', 'Kategoria(s)', 1))
  dialogs: 
    kategoriaDel_dialog: 
      <<: *Kategoria
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Kategoria', 'Kategoria(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Kategoria', 'Kategoria(s)', 1))
      message: _("%s successfully deleted.", ngettext('Kategoria', 'Kategoria(s)', 1))
      labelOnList: true
      multiItem: true

testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production