#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: kategoriaGlobalaList_screen
  screens: &kategoriaGlobala_screensLink 
    kategoriaGlobalaList_screen: &kategoriaGlobalaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *KategoriaGlobala
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Kategoria globala', 'Kategoria globala(s)', 0), "[format| (%parent%)]")
      fields: &kategoriaGlobala_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            kategoriaGlobalaEdit_screen: true
          dialogs: 
            kategoriaGlobalaDel_dialog: true
          default: kategoriaGlobalaEdit_screen
      options: 
        title: _("Options")
        screens: 
          kategoriaGlobalaNew_screen: true
        dialogs: 
          kategoriaGlobalaDel_dialog: true
    kategoriaGlobalaNew_screen: &kategoriaGlobalaNew_screenLink 
      <<: *KategoriaGlobala
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Kategoria globala', 'Kategoria globala(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          kategoriaGlobalaEdit_screen: true
      fields: 
        blacklist: 
          url: true
    kategoriaGlobalaEdit_screen: &kategoriaGlobalaEdit_screenLink 
      <<: *KategoriaGlobala
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Kategoria globala', 'Kategoria globala(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Kategoria globala', 'Kategoria globala(s)', 1), "[format| (%item%)]")
  dialogs: &kategoriaGlobala_dialogsLink 
    kategoriaGlobalaDel_dialog: &kategoriaGlobalaDel_dialogLink 
      <<: *KategoriaGlobala
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Kategoria globala', 'Kategoria globala(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Kategoria globala', 'Kategoria globala(s)', 1))
      message: _("%s successfully deleted.", ngettext('Kategoria globala', 'Kategoria globala(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: &kategoriaGlobala_commandsLink 
    kategoriaGlobalaIrudiaDownload_command: &kategoriaGlobalaIrudiaDownload_commandLink 
      <<: *KategoriaGlobala
      controller: File
      action: force-download
      mainColumn: irudia
    kategoriaGlobalaIrudiaUpload_command: &kategoriaGlobalaIrudiaUpload_commandLink 
      <<: *KategoriaGlobala
      controller: File
      action: upload
      mainColumn: irudia
    kategoriaGlobalaIrudiaPreview_command: &kategoriaGlobalaIrudiaPreview_commandLink 
      <<: *KategoriaGlobala
      controller: File
      action: preview
      mainColumn: irudia
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
