#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: literalesList_screen
  screens: 
    literalesList_screen: &literalesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Literales
      title: _("List of %s %2s", ngettext('Literale', 'Literales', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            literalesEdit_screen: true
          dialogs: 
            literalesDel_dialog: true
          default: literalesEdit_screen
      options: 
        title: _("Options")
        screens: 
          literalesNew_screen: true
        dialogs: 
          literalesDel_dialog: true
    literalesNew_screen: &literalesNew_screenLink 
      <<: *Literales
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Literale', 'Literales', 1))
      shortcutOption: N
    literalesEdit_screen: &literalesEdit_screenLink 
      <<: *Literales
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Literale', 'Literales', 1), "[format| (%item%)]")
  dialogs: 
    literalesDel_dialog: 
      <<: *Literales
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Literale', 'Literales', 1))
      description: _("Do you want to delete this %s?", ngettext('Literale', 'Literales', 1))
      message: _("%s successfully deleted.", ngettext('Literale', 'Literales', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
