#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedMaila
    fixedPositions:
      group1:
        label: _("Mailaren datuak")
        colsPerRow: 4
        fields:
          izena: 2
          url: 2

production: 
  main: 
    module: klearMatrix
    defaultScreen: mailaList_screen
  screens: 
    mailaList_screen: &mailaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Maila
      title: _("Mailen zerrenda")
      fields: 
        blacklist:
          url: true
        options: 
          title: _("Options")
          screens: 
            mailaEdit_screen: true
          dialogs: 
            mailaDel_dialog: true
          default: mailaEdit_screen
      options: 
        title: _("Options")
        screens: 
          mailaNew_screen: true
        dialogs: 
          mailaDel_dialog: true
    mailaNew_screen: &mailaNew_screenLink 
      <<: *Maila
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Maila', 'Maila(s)', 1))
      <<: *fixedMaila
      fields: 
        blacklist: 
          url: true
    mailaEdit_screen: &mailaEdit_screenLink 
      <<: *Maila
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Maila', 'Maila(s)', 1), "[format| (%item%)]")
      <<: *fixedMaila
  dialogs: 
    mailaDel_dialog: 
      <<: *Maila
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Maila', 'Maila(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Maila', 'Maila(s)', 1))
      message: _("%s successfully deleted.", ngettext('Maila', 'Maila(s)', 1))
      labelOnList: true
      multiItem: true

testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
