#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: mezuakList_screen
  screens: 
    mezuakList_screen: &mezuakList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Mezuak
      title: _("List of %s", ngettext('Mezuak', 'Mezuak(s)', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            mezuakEdit_screen: true
          dialogs: 
            mezuakDel_dialog: true
          default: mezuakEdit_screen
      options: 
        title: _("Options")
        screens: 
          mezuakNew_screen: true
        dialogs: 
          mezuakDel_dialog: true
    mezuakNew_screen: &mezuakNew_screenLink 
      <<: *Mezuak
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Mezuak', 'Mezuak(s)', 1))
      fields: 
        blacklist: 
          sortzeData: true
    mezuakEdit_screen: &mezuakEdit_screenLink 
      <<: *Mezuak
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Mezuak', 'Mezuak(s)', 1))
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: 
    mezuakDel_dialog: 
      <<: *Mezuak
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Mezuak', 'Mezuak(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Mezuak', 'Mezuak(s)', 1))
      message: _("%s successfully deleted.", ngettext('Mezuak', 'Mezuak(s)', 1))
      labelOnList: true
      multiItem: true
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
