#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: notifikazioaList_screen
  screens: 
    notifikazioaList_screen: &notifikazioaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Notifikazioa
      title: _("List of %s %2s", ngettext('Notifikazioa', 'Notifikazioa(s)', 0), "[format| (%parent%)]")
      fields: 
        blacklist:
          edukiaHtml: true
          edukiaText: true
        options: 
          title: _("Options")
          screens: 
            notifikazioaEdit_screen: true
          dialogs: 
            notifikazioaDel_dialog: true
          default: notifikazioaEdit_screen
      options: 
        title: _("Options")
        screens: 
          notifikazioaNew_screen: true
        dialogs: 
          notifikazioaDel_dialog: true
    notifikazioaNew_screen: &notifikazioaNew_screenLink 
      <<: *Notifikazioa
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Notifikazioa', 'Notifikazioa(s)', 1))
    notifikazioaEdit_screen: &notifikazioaEdit_screenLink 
      <<: *Notifikazioa
      controller: edit
      class: ui-silk-pencil
      label: false
      fields: 
        blacklist:
          identifikatzailea: true
      title: _("Edit %s %2s", ngettext('Notifikazioa', 'Notifikazioa(s)', 1), "[format| (%item%)]")
  dialogs: 
    notifikazioaDel_dialog: 
      <<: *Notifikazioa
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Notifikazioa', 'Notifikazioa(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Notifikazioa', 'Notifikazioa(s)', 1))
      message: _("%s successfully deleted.", ngettext('Notifikazioa', 'Notifikazioa(s)', 1))
      labelOnList: true
      multiItem: true

testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
