#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedOrria
    fixedPositions:
      group0:
        label: _("Datuak")
        colsPerRow: 4
        fields:
          titulua: 2
          publikatua: 2
          url: 2

production: 
  main: 
    module: klearMatrix
    defaultScreen: orrialdeaList_screen
  screens: 
    orrialdeaList_screen: &orrialdeaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Orrialdea
      title: _("List of %s", ngettext('Orrialdea', 'Orrialdea(s)', 0))
      fields:
        blacklist:
          edukia: true
          metaDescription: true
        options: 
          title: _("Options")
          screens: 
            orrialdeaEdit_screen: true
          dialogs: 
            orrialdeaDel_dialog: true
          default: orrialdeaEdit_screen
      options: 
        title: _("Options")
        screens: 
          orrialdeaNew_screen: true
        dialogs: 
          orrialdeaDel_dialog: true
    orrialdeaNew_screen: &orrialdeaNew_screenLink 
      <<: *Orrialdea
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Orrialdea', 'Orrialdea(s)', 1))
      <<: *fixedOrria
      fields: 
        blacklist: 
          sortzeData: true
          url: true

    orrialdeaEdit_screen: &orrialdeaEdit_screenLink 
      <<: *Orrialdea
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Orrialdea', 'Orrialdea(s)', 1))
      <<: *fixedOrria
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: 
    orrialdeaDel_dialog: 
      <<: *Orrialdea
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Orrialdea', 'Orrialdea(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Orrialdea', 'Orrialdea(s)', 1))
      message: _("%s successfully deleted.", ngettext('Orrialdea', 'Orrialdea(s)', 1))
      labelOnList: true
      multiItem: true
  commands: 
    ImgDownload_command: 
      <<: *Orrialdea
      controller: File
      action: force-download
      mainColumn: img
    ImgUpload_command: 
      <<: *Orrialdea
      controller: File
      action: upload
      mainColumn: img
    ImgPreview_command: 
      <<: *Orrialdea
      controller: File
      action: preview
      mainColumn: img
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
