<section class="col-xs-12 aire">

    <?php
        echo $this->alertMessage(
            $this->erroreMezuak,
            $this->flashmezuak,
            $this->alertWarning
        );
    ?>

    <form class="form-horizontal col-sm-8 col-sm-offset-2" method="POST" action="" autocomplete="off">

        <div class="form-group">

            <label for="erabiltzailea" class="col-sm-2 control-label">Erabiltzailea</label>

            <div class="col-sm-10">
                <input
                    type="text"
                    class="form-control"
                    id="erabiltzailea"
                    name="erabiltzailea"
                    placeholder="Erabiltzailea"
                    autofocus="autofocus"
                    value=""
                    />
            </div>

        </div>

        <div class="form-group">

            <label for="easahitza" class="col-sm-2 control-label">Pasahitza</label>

            <div class="col-sm-10">
                <input
                    type="password"
                    class="form-control"
                    id="pasahitza"
                    name="pasahitza"
                    placeholder="Pasahitza"
                    value=""
                    />
            </div>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                <label>
                    <input type="checkbox" name="gogoratu" value="true"> Gogoratu
                </label>
                </div>
            </div>
        </div>

        <input
            type="hidden"
            name="referer"
            value="<?php echo $this->referer; ?>"
            />

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="save" value="true" class="btn btn-success">Bidali</button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <a
                    href="<?php echo $this->baseUrl('?izena-eman=true')?>"
                    title="Izena eman"
                    >Izena eman</a> -
                <a
                    href="<?php echo $this->baseUrl('/pasahitza-berreskuratu/')?>"
                    title="Pasahitza Berreskuratu"
                    >Pasahitza Berreskuratu</a>
            </div>
        </div>

    </form>
</section>