<div class="resumen-categoria {{width}} {{class}}">
    <figure>

        <img src="{{kategoriaIrudia}}" alt="{{kategoriaIzena}}" style="height: 155px;" />

        <figcaption class="col-xs-12 categoria {{kategoriaGlobalaClassName}}">
            <span class="category">
                <a href="{{kategoriaUrl}}">{{kategoriaIzena}}</a>
            </span>
            <span class="cantidad-recurso">
                <strong>{{kategoriaEdukiakCount}}</strong> baliabide
            </span>
        </figcaption>
    </figure>
</div>
