<div class="container principal">

    <div class="col-xs-12 subheader bg-standard-grey">
        <h1>Lizentziak</h1>
    </div>

    <div class="col-xs-12">
        <br />
    </div>

    <br />

    <div class="row">
        <div class="col-xs-12">
            <h2>Creative Commons</h2>
        </div>
        <div class="col-xs-10 col-xs-offset-1">
            <?php echo $this->lizentzia; ?>
        </div>
    </div>



    <div>
        <div class="col-xs-12">
            <h2 class="credits-title">Software kredituak</h2>
        </div>
	        <div class="col-xs-6 col-sm-3 pull-left">
	            <div class="row">
	                <div class="row text-center">

	                    <img src="http://php.net/images/logos/php-med-trans-light.gif" alt="php" />
	                    <br />
	                    <a href="http://www.php.net/">
	                        PHP
	                    </a>
	                </div>
	            </div><!-- .row -->
	            <br />
	        </div>
	        <div class="col-xs-6 col-sm-3 pull-left">
	            <div class="row">
	                <div class="row text-center">

	                    <img src="http://www.mysql.com/common/logos/powered-by-mysql-125x64.png" alt="mysql" />
	                    <br />
	                    <a href="http://www.mysql.com/">
	                        MySql
	                    </a>
	                </div>
	            </div><!-- .row -->
	            <br />
	        </div>
	        <div class="col-xs-6 col-sm-3 pull-left">
	            <div class="row">
	                <div class="row text-center">

	                    <img src="<?php echo $this->baseUrl("img/klear.png"); ?>" alt="php" />
	                    <br />
	                    <a href="https://github.com/irontec/klear-full">
	                        Klear
	                    </a>

	                </div>
	            </div><!-- .row -->
	            <br />
	        </div>

	        <div class="col-xs-6 col-sm-3 pull-left">
	            <div class="row">
	                <div class="row text-center">

	                    <img src="https://www.debian.org/logos/openlogo-nd-75.jpg" alt="debian" />
	                    <br />
	                    <a href="http://www.debian.org/">
	                        Debian
	                    </a>
	                </div>
	            </div><!-- .row -->
	            <br />
	        </div>
    </div>
    <br style="clear:both;" />
    <div>
        <div class="col-xs-12">
            <h2 class="credits-title">Irudien Kredituak</h2>
        </div>
        <div class="col-xs-12 col-sm-6 pull-left">

            <div class="row">

                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/eriwst/2421129047/sizes/o/in/photostream/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/27/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/eriwst/2421129047/sizes/o/in/photostream/"
                            style="width: 75%"
                            /></a>

                    <br />
    				<div class="legend">
	                    <a
	                        href="https://www.flickr.com/photos/eriwst/"
	                        target="_blank"
	                        title="Eric Wüstenhagen"
	                        >Eric Wüstenhagen</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

            <div class="row">

                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/tabor-roeder/8113284229/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/29/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/tabor-roeder/8113284229/"
                            style="width: 75%"
                            /></a>

                    <br />
        			<div class="legend">
	                    <a
	                        href="https://www.flickr.com/photos/tabor-roeder/"
	                        target="_blank"
	                        title="Phil Roeder"
	                        >Phil Roeder</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

            <div class="row">

                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/malinhelene/3846635438/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/28/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/malinhelene/3846635438/"
                            style="width: 75%"
                            /></a>

                    <br />
        			<div class="legend">
	                    <a
	                        href="https://www.flickr.com/photos/malinhelene/"
	                        target="_blank"
	                        title="Malin Andreassen"
	                        >Malin Andreassen</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

            <div class="row">

                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/davideragusa/11523630834/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/20/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/davideragusa/11523630834/"
                            style="width: 75%"
                            /></a>

                    <br />
        			<div class="legend">
	                    <a
	                        href="https://www.flickr.com/photos/davideragusa/"
	                        target="_blank"
	                        title="Davide Ragusa"
	                        >Davide Ragusa</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

        </div><!-- .col-xs-12.col-sm-6.pull-left -->

        <div class="col-xs-12 col-sm-6">

            <div class="row">
                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/aigle_dore/6365101775/in/photolist-aGsP14-7PozJp-84P71r-dphot9-5qz3ks-eqHuv-6NP8d6-HdurS-aibaen-6buevW-7acJMF-8DFBf3-MLnGM-88og6h-r7w3U-2qKgwi-mcp7h-5RzRtp-7JKRHh-6iUdMZ-2bUDT-9k6cM-8s4PDi-8pvSWc-dynb6k-zV2x5-dsxGqc-b4jsc2-8YyqSQ-9ggca5-89NBaJ-4PNHrt-7JGpz4-q1ic-sZMVW-84NAEC-8JBSSW-bGRT8X-6i3K7f-aGsPSg-a9R8Ca-a9TVmy-9RGVDW-4xWMzG-aL22G2-7WgBCp-ezKcG-2SgRsM-7Cby3b-5wHRbh/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/19/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/aigle_dore/6365101775/in/photolist-aGsP14-7PozJp-84P71r-dphot9-5qz3ks-eqHuv-6NP8d6-HdurS-aibaen-6buevW-7acJMF-8DFBf3-MLnGM-88og6h-r7w3U-2qKgwi-mcp7h-5RzRtp-7JKRHh-6iUdMZ-2bUDT-9k6cM-8s4PDi-8pvSWc-dynb6k-zV2x5-dsxGqc-b4jsc2-8YyqSQ-9ggca5-89NBaJ-4PNHrt-7JGpz4-q1ic-sZMVW-84NAEC-8JBSSW-bGRT8X-6i3K7f-aGsPSg-a9R8Ca-a9TVmy-9RGVDW-4xWMzG-aL22G2-7WgBCp-ezKcG-2SgRsM-7Cby3b-5wHRbh/"
                            style="width: 75%"
                            /></a>

                    <br />
        			<div class="legend">

	                    <a
	                        href="https://www.flickr.com/photos/aigle_dore/"
	                        target="_blank"
	                        title="Moyan Brenn"
	                        >Moyan Brenn</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

            <div class="row">
                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/ektogamat/2103643766/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/31/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/ektogamat/2103643766/"
                            style="width: 75%"
                            /></a>

                    <br />

        			<div class="legend">

	                    <a
	                        href="https://www.flickr.com/photos/ektogamat/"
	                        target="_blank"
	                        title="Anderson Mancini"
	                        >Anderson Mancini</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

            <div class="row">
                <div class="row text-center">

                    <a
                        href="https://www.flickr.com/photos/berenicedecados/6187621870/sizes/o/in/photostream/"
                        target="_blank"
                        ><img
                            src="<?php echo $this->baseUrl('image/index/id/30/view/kategoriaGlobala/size/simple/'); ?>"
                            alt="https://www.flickr.com/photos/berenicedecados/6187621870/sizes/o/in/photostream/"
                            style="width: 75%"
                            /></a>

                    <br />
        			<div class="legend">

	                    <a
	                        href="https://www.flickr.com/photos/berenicedecados/"
	                        target="_blank"
	                        title="Anderson Mancini"
	                        >Romina Campos</a>

	                    <span class="ccIcn ccIcnSmall">
	                        <a href="https://creativecommons.org/licenses/by-sa/2.0/">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_attribution_small.gif" border="0" alt="Atribuzioa" title="Atribuzioa">
	                            <img src="https://s.yimg.com/pw/images/cc_icon_sharealike_small.gif" border="0" alt="Lizentzia berdinarekin partekatu" title="Lizentzia berdinarekin partekatu">
	                        </a>
	                    </span>
    				</div>
                </div>

            </div><!-- .row -->

            <br />

        </div><!-- .col-xs-12.col-sm-6 -->
    </div>
</div>
