<div class="bloque-destacado row {{fondo-color}}" {{#backgroundImagen}}style="background : url('{{backgroundImagen}}') 50% 50%; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;"{{/backgroundImagen}}>
    <div class="container  col-md-6 col-md-offset-3 text-center light p-top-4 p-bottom-4 aire">
        <header class="content aire">
                <h1>{{title}}</h1>
        </header>

        <p>{{description}}</p>

        {{#button}}<button data-url="{{batu}}" class="{{button-class}}">{{button}}</button>{{/button}}

    </div>
</div>
