<section class="esquema-home">
    <div class="container">
        <header class="p-bottom-3 p-top-3 content aire">
            <h2>Guztion artean osatzen dugu Klikasi</h2>
            <small>Edukiak partekatu, zabaldu eta ikasi</small>
        </header>
    </div>
    
    <div class="container">
        <img id="esquema-flecha-1" src="{{arrow-1}}" alt="Flechas"/>
        <img id="esquema-flecha-2" src="{{arrow-2}}" alt="Flechas"/>
        
        <div class="row text-center">
            
            {{#outline}}
                {{> outline-content}}
            {{/outline}}
            
        </div>
    </div>
    
</section>