<small class="info-ficha pull-right">
    <span class="cont">
        <i class="fa fa-eye"></i>
        <span class="moreViews">{{infoEdukia.moreViews}}</span>
    </span>
    <span class="cont">
        <span class="glyphicon glyphicon-heart-empty"></span>
        <span class="moreLikes">{{infoEdukia.moreLikes}}</span>
    </span>
    <span class="cont">
        <i class="fa fa-comments"></i>
        <span class="moreComments">{{infoEdukia.countComments}}</span>
    </span>
</small>
