<div class="resumen-categoria col-xs-12 col-sm-4 destacada">
    <figure>
        <img class="ficha-img" src="{{KategoriaGlobalaIrudia}}" alt="{{KategoriaGlobalaIzena}}" style="width: 100%" />
        <figcaption class="col-xs-12 categoria {{KategoriaGlobalaClassName}}">
            <span class="category">
                <a href="{{KategoriaUrl}}" title="{{KategoriaIzena}}">{{KategoriaIzena}}</a>
            </span>
            <span class="cantidad-recurso"><strong class="moreData">{{KategoriaEdukiakCount}}</strong> baliabide</span>
        </figcaption>
    </figure>
</div>
