<div class="resumen-categoria col-xs-12 col-sm-4 col-md-3">
    <figure>
        <img class="ficha-img" src="{{KategoriaGlobalaIrudia}}" alt="{{KategoriaGlobalaIzena}}" style="width: 100%; min-height: 191px; min-width:263px;" />
        <figcaption class="col-xs-12 categoria {{KategoriaGlobalaClassName}}">
            <span class="category">
                <a href="{{KategoriaUrl}}" title="{{KategoriaIzena}}">{{KategoriaIzena}}</a>
            </span>
            <span class="cantidad-recurso"><strong class="moreData">{{KategoriaEdukiakCount}}</strong> baliabide</span>
            <span class="moreBisita hide">{{edukiakBisitaKopuruaSum}}</span>
            <span class="moreUpdate hide">{{edukiakSortzeData}}</span>
        </figcaption>
    </figure>
</div>
