#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: bideoaList_screen
  screens: &bideoa_screensLink 
    bideoaList_screen: &bideoaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Bideoa
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Bideoa', 'Bideoa(s)', 0), "[format| (%parent%)]")
      fields: &bideoa_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            bideoaEdit_screen: true
          dialogs: 
            bideoaDel_dialog: true
          default: bideoaEdit_screen
      options: 
        title: _("Options")
        screens: 
          bideoaNew_screen: true
        dialogs: 
          bideoaDel_dialog: true
    bideoaNew_screen: &bideoaNew_screenLink 
      <<: *Bideoa
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Bideoa', 'Bideoa(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          bideoaEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    bideoaEdit_screen: &bideoaEdit_screenLink 
      <<: *Bideoa
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Bideoa', 'Bideoa(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Bideoa', 'Bideoa(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: &bideoa_dialogsLink 
    bideoaDel_dialog: &bideoaDel_dialogLink 
      <<: *Bideoa
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Bideoa', 'Bideoa(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Bideoa', 'Bideoa(s)', 1))
      message: _("%s successfully deleted.", ngettext('Bideoa', 'Bideoa(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
