#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: estekaList_screen
  screens: &esteka_screensLink 
    estekaList_screen: &estekaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Esteka
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Esteka', 'Esteka(s)', 0), "[format| (%parent%)]")
      fields: &esteka_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            estekaEdit_screen: true
          dialogs: 
            estekaDel_dialog: true
          default: estekaEdit_screen
      options: 
        title: _("Options")
        screens: 
          estekaNew_screen: true
        dialogs: 
          estekaDel_dialog: true
    estekaNew_screen: &estekaNew_screenLink 
      <<: *Esteka
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Esteka', 'Esteka(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          estekaEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    estekaEdit_screen: &estekaEdit_screenLink 
      <<: *Esteka
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Esteka', 'Esteka(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Esteka', 'Esteka(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: &esteka_dialogsLink 
    estekaDel_dialog: &estekaDel_dialogLink 
      <<: *Esteka
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Esteka', 'Esteka(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Esteka', 'Esteka(s)', 1))
      message: _("%s successfully deleted.", ngettext('Esteka', 'Esteka(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
