#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: fitxategiaList_screen
  screens: &fitxategia_screensLink 
    fitxategiaList_screen: &fitxategiaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Fitxategia
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Fitxategia', 'Fitxategia(s)', 0), "[format| (%parent%)]")
      fields: &fitxategia_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            fitxategiaEdit_screen: true
          dialogs: 
            fitxategiaDel_dialog: true
          default: fitxategiaEdit_screen
      options: 
        title: _("Options")
        screens: 
          fitxategiaNew_screen: true
        dialogs: 
          fitxategiaDel_dialog: true
    fitxategiaNew_screen: &fitxategiaNew_screenLink 
      <<: *Fitxategia
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Fitxategia', 'Fitxategia(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          fitxategiaEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    fitxategiaEdit_screen: &fitxategiaEdit_screenLink 
      <<: *Fitxategia
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Fitxategia', 'Fitxategia(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Fitxategia', 'Fitxategia(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: &fitxategia_dialogsLink 
    fitxategiaDel_dialog: &fitxategiaDel_dialogLink 
      <<: *Fitxategia
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Fitxategia', 'Fitxategia(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Fitxategia', 'Fitxategia(s)', 1))
      message: _("%s successfully deleted.", ngettext('Fitxategia', 'Fitxategia(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: &fitxategia_commandsLink 
    fitxategiaFitxategiaDownload_command: &fitxategiaFitxategiaDownload_commandLink 
      <<: *Fitxategia
      controller: File
      action: force-download
      mainColumn: fitxategia
    fitxategiaFitxategiaUpload_command: &fitxategiaFitxategiaUpload_commandLink 
      <<: *Fitxategia
      controller: File
      action: upload
      mainColumn: fitxategia
    fitxategiaFitxategiaPreview_command: &fitxategiaFitxategiaPreview_commandLink 
      <<: *Fitxategia
      controller: File
      action: preview
      mainColumn: fitxategia
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
