#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: irudiaList_screen
  screens: &irudia_screensLink 
    irudiaList_screen: &irudiaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Irudia
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Irudia', 'Irudia(s)', 0), "[format| (%parent%)]")
      fields: &irudia_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            irudiaEdit_screen: true
          dialogs: 
            irudiaDel_dialog: true
          default: irudiaEdit_screen
      options: 
        title: _("Options")
        screens: 
          irudiaNew_screen: true
        dialogs: 
          irudiaDel_dialog: true
    irudiaNew_screen: &irudiaNew_screenLink 
      <<: *Irudia
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Irudia', 'Irudia(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          irudiaEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    irudiaEdit_screen: &irudiaEdit_screenLink 
      <<: *Irudia
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Irudia', 'Irudia(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Irudia', 'Irudia(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: &irudia_dialogsLink 
    irudiaDel_dialog: &irudiaDel_dialogLink 
      <<: *Irudia
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Irudia', 'Irudia(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Irudia', 'Irudia(s)', 1))
      message: _("%s successfully deleted.", ngettext('Irudia', 'Irudia(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: &irudia_commandsLink 
    irudiaFitxategiaDownload_command: &irudiaFitxategiaDownload_commandLink 
      <<: *Irudia
      controller: File
      action: force-download
      mainColumn: fitxategia
    irudiaFitxategiaUpload_command: &irudiaFitxategiaUpload_commandLink 
      <<: *Irudia
      controller: File
      action: upload
      mainColumn: fitxategia
    irudiaFitxategiaPreview_command: &irudiaFitxategiaPreview_commandLink 
      <<: *Irudia
      controller: File
      action: preview
      mainColumn: fitxategia
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
