#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: iruzkinaList_screen
  screens: &iruzkina_screensLink 
    iruzkinaList_screen: &iruzkinaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Iruzkina
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Iruzkina', 'Iruzkina(s)', 0), "[format| (%parent%)]")
      fields: &iruzkina_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            iruzkinaEdit_screen: true
          dialogs: 
            iruzkinaDel_dialog: true
          default: iruzkinaEdit_screen
      options: 
        title: _("Options")
        screens: 
          iruzkinaNew_screen: true
        dialogs: 
          iruzkinaDel_dialog: true
    iruzkinaNew_screen: &iruzkinaNew_screenLink 
      <<: *Iruzkina
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Iruzkina', 'Iruzkina(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          iruzkinaEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    iruzkinaEdit_screen: &iruzkinaEdit_screenLink 
      <<: *Iruzkina
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Iruzkina', 'Iruzkina(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Iruzkina', 'Iruzkina(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: &iruzkina_dialogsLink 
    iruzkinaDel_dialog: &iruzkinaDel_dialogLink 
      <<: *Iruzkina
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Iruzkina', 'Iruzkina(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Iruzkina', 'Iruzkina(s)', 1))
      message: _("%s successfully deleted.", ngettext('Iruzkina', 'Iruzkina(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
