#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include JakinarazpenakGroupList.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: jakinarazpenakList_screen
  screens: &jakinarazpenak_screensLink 
    jakinarazpenakList_screen: &jakinarazpenakList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Jakinarazpenak
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 0), "[format| (%parent%)]")
      fields: &jakinarazpenak_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            jakinarazpenakEdit_screen: true
            jakinarazpenakGroupList_screen: true
          dialogs: 
            jakinarazpenakDel_dialog: true
          default: jakinarazpenakEdit_screen
      options: 
        title: _("Options")
        screens: 
          jakinarazpenakNew_screen: true
        dialogs: 
          jakinarazpenakDel_dialog: true
    jakinarazpenakNew_screen: &jakinarazpenakNew_screenLink 
      <<: *Jakinarazpenak
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          jakinarazpenakEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    jakinarazpenakEdit_screen: &jakinarazpenakEdit_screenLink 
      <<: *Jakinarazpenak
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
    #jakinarazpenakGroup: 
    <<: *jakinarazpenakGroup_screensLink
    jakinarazpenakGroupList_screen: 
      <<: *jakinarazpenakGroupList_screenLink
      filterField: jakinarazpenakId
      parentOptionCustomizer: 
        - recordCount
    jakinarazpenakGroupNew_screen: 
      <<: *jakinarazpenakGroupNew_screenLink
      filterField: jakinarazpenakId
    jakinarazpenakGroupEdit_screen: 
      <<: *jakinarazpenakGroupEdit_screenLink
      filterField: jakinarazpenakId

  dialogs: &jakinarazpenak_dialogsLink 
    jakinarazpenakDel_dialog: &jakinarazpenakDel_dialogLink 
      <<: *Jakinarazpenak
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 1))
      message: _("%s successfully deleted.", ngettext('Jakinarazpenak', 'Jakinarazpenak(s)', 1))
      multiItem: 1
      labelOnList: 1
  # jakinarazpenakGroup dialogs: 
    <<: *jakinarazpenakGroup_dialogsLink
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
