#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include JakinarazpenakList.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: jakinarazpenakMotaList_screen
  screens: &jakinarazpenakMota_screensLink 
    jakinarazpenakMotaList_screen: &jakinarazpenakMotaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *JakinarazpenakMota
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 0), "[format| (%parent%)]")
      fields: &jakinarazpenakMota_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            jakinarazpenakMotaEdit_screen: true
            jakinarazpenakList_screen: true
          dialogs: 
            jakinarazpenakMotaDel_dialog: true
          default: jakinarazpenakMotaEdit_screen
      options: 
        title: _("Options")
        screens: 
          jakinarazpenakMotaNew_screen: true
        dialogs: 
          jakinarazpenakMotaDel_dialog: true
    jakinarazpenakMotaNew_screen: &jakinarazpenakMotaNew_screenLink 
      <<: *JakinarazpenakMota
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          jakinarazpenakMotaEdit_screen: true
      fields: 
        blacklist: 
          url: true
    jakinarazpenakMotaEdit_screen: &jakinarazpenakMotaEdit_screenLink 
      <<: *JakinarazpenakMota
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 1), "[format| (%item%)]")
    #jakinarazpenak: 
    <<: *jakinarazpenak_screensLink
    jakinarazpenakList_screen: 
      <<: *jakinarazpenakList_screenLink
      filterField: motaId
      parentOptionCustomizer: 
        - recordCount
    jakinarazpenakNew_screen: 
      <<: *jakinarazpenakNew_screenLink
      filterField: motaId
    jakinarazpenakEdit_screen: 
      <<: *jakinarazpenakEdit_screenLink
      filterField: motaId

  dialogs: &jakinarazpenakMota_dialogsLink 
    jakinarazpenakMotaDel_dialog: &jakinarazpenakMotaDel_dialogLink 
      <<: *JakinarazpenakMota
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 1))
      message: _("%s successfully deleted.", ngettext('Jakinarazpenak mota', 'Jakinarazpenak mota(s)', 1))
      multiItem: 1
      labelOnList: 1
  # jakinarazpenak dialogs: 
    <<: *jakinarazpenak_dialogsLink
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
