#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: kategoriaList_screen
  screens: &kategoria_screensLink 
    kategoriaList_screen: &kategoriaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Kategoria
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Kategoria', 'Kategoria(s)', 0), "[format| (%parent%)]")
      fields: &kategoria_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            kategoriaEdit_screen: true
          dialogs: 
            kategoriaDel_dialog: true
          default: kategoriaEdit_screen
      options: 
        title: _("Options")
        screens: 
          kategoriaNew_screen: true
        dialogs: 
          kategoriaDel_dialog: true
    kategoriaNew_screen: &kategoriaNew_screenLink 
      <<: *Kategoria
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Kategoria', 'Kategoria(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          kategoriaEdit_screen: true
      fields: 
        blacklist: 
          url: true
    kategoriaEdit_screen: &kategoriaEdit_screenLink 
      <<: *Kategoria
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Kategoria', 'Kategoria(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Kategoria', 'Kategoria(s)', 1), "[format| (%item%)]")
  dialogs: &kategoria_dialogsLink 
    kategoriaDel_dialog: &kategoriaDel_dialogLink 
      <<: *Kategoria
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Kategoria', 'Kategoria(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Kategoria', 'Kategoria(s)', 1))
      message: _("%s successfully deleted.", ngettext('Kategoria', 'Kategoria(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
