#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production: 
  main: 
    module: klearMatrix
    defaultScreen: mezuakList_screen
  screens: &mezuak_screensLink 
    mezuakList_screen: &mezuakList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Mezuak
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Mezuak', 'Mezuak(s)', 0), "[format| (%parent%)]")
      fields: &mezuak_fieldsLink 
        options: 
          title: _("Options")
          screens: 
            mezuakEdit_screen: true
          dialogs: 
            mezuakDel_dialog: true
          default: mezuakEdit_screen
      options: 
        title: _("Options")
        screens: 
          mezuakNew_screen: true
        dialogs: 
          mezuakDel_dialog: true
    mezuakNew_screen: &mezuakNew_screenLink 
      <<: *Mezuak
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Mezuak', 'Mezuak(s)', 1), "[format| (%parent%)]")
      shortcutOption: N
      postActionOptions: 
        screens: 
          mezuakEdit_screen: true
      fields: 
        blacklist: 
          sortzeData: true
    mezuakEdit_screen: &mezuakEdit_screenLink 
      <<: *Mezuak
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Mezuak', 'Mezuak(s)', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Mezuak', 'Mezuak(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          sortzeData: true
  dialogs: &mezuak_dialogsLink 
    mezuakDel_dialog: &mezuakDel_dialogLink 
      <<: *Mezuak
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Mezuak', 'Mezuak(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Mezuak', 'Mezuak(s)', 1))
      message: _("%s successfully deleted.", ngettext('Mezuak', 'Mezuak(s)', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
