<!-- carousel-multi.hbs -->

<div id="{{id}}" class="carousel multi slide {{class}} hidden-xs" data-ride="carousel">

    <!-- Indicators -->
    <ol class="carousel-indicators">
        {{#slides}}
            {{#elems}}
                <li data-target="#{{id}}" data-slide-to="{{position}}" class="{{class}}"></li>
            {{/elems}}
        {{/slides}}
    </ol>

  <!-- Wrapper for slides -->
    <div class="carousel-inner">
        {{#slides}}
            <div class="item {{class}}">
                {{#elems}}
                    <div class="elem {{class}}">
                        <div class="content type-image">
                            <figure>
                                {{#url}}
                                    <a href="{{url}}">
                                {{/url}}
                                <img src="{{image}}" alt="{{alt}}" />
                                {{#url}}
                                    </a>
                                {{/url}}

                                {{#url}}
                                    <a href="{{url}}">
                                {{/url}}
                                <figcaption>
                                    <h4>
                                        {{title}}
                                    </h4>
                                    <p>{{description}}</p>
                                </figcaption>
                                {{#url}}
                                    </a>
                                {{/url}}
                            </figure>
                        </div>
                    </div>
                {{/elems}}

                {{#header}}
                    {{#url}}
                        <a href="{{url}}">
                    {{/url}}
                    <h3>{{header}}</h3>
                    <p>{{title}}</p>
                    {{#url}}
                        </a>
                    {{/url}}
                    <p>{{desc}}</p>
                {{/header}}
            </div>
        {{/slides}}
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#{{id}}" data-slide="prev">
        <span class="fa fa-chevron-circle-left"></span>
    </a>

    <a class="right carousel-control" href="#{{id}}" data-slide="next">
        <span class="fa fa-chevron-circle-right"></span>
    </a>
</div>

<!--  -->

<div id="{{id}}-xs" class="col-xs-12 carousel multi slide {{class}} hidden-sm hidden-md hidden-lg" data-ride="carousel">

    <!-- Indicators -->
    <ol class="carousel-indicators">
        {{#slides}}
            {{#elems}}
                <li data-target="#{{id}}-xs" data-slide-to="{{position}}" class="{{class-xs}}"></li>
            {{/elems}}
        {{/slides}}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        {{#slides}}
            {{#elems}}
                <div class="item {{active-xs}}">
                    <div class="elem {{class}}">
                        <div class="content
                                        {{#type-image}}
                                            type-image
                                        {{/type-image}}

                                        {{^type-image}}

                                            {{#type-image-text}}
                                                type-image-text
                                            {{/type-image-text}}

                                            {{^type-image-text}}
                                                {{fondo}}
                                            {{/type-image-text}}

                                        {{/type-image}}
                                        ">

                            {{#type-text}}
                                {{#url}}
                                	<a href="{{url}}">
                                {{/url}}
                                <h4>{{title}}</h4>
                                {{#url}}
                                	</a>
	                            {{/url}}
                                {{description}}

                            {{/type-text}}

                            {{^type-text}}

                                {{#type-image}}

                                    <figure>
                                        <img src="{{image}}" alt="{{alt}}" />
                                    </figure>

                                {{/type-image}}

                                {{^type-image}}

                                    {{#type-image-text}}
                                        <figure>

                                            <img src="{{image}}" alt="{{alt}}" />
                                            {{#url}}
                                                <a href="{{url}}">
                                            {{/url}}
                                            <figcaption>
                                                <h4>{{title}}</h4>

                                                <p>{{description}}</p>
                                            </figcaption>
                                            {{#url}}
                                                </a>
                                            {{/url}}
                                        </figure>
                                    {{/type-image-text}}

                                {{/type-image}}

                            {{/type-text}}

                        </div>
                    </div>
                </div>
            {{/elems}}
        {{/slides}}
    </div>

</div>