<div class="modal" id="blokeatutaEdukiakDialog" data-jakinarazpena="">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">
                <h4><?php echo $this->translate('[es] Bloquear Recurso:'); ?> <em></em></h4>
            </div>

            <div class="modal-body">

                <p class="textDescription"><?php echo $this->translate('[es] ¿Esta seguro que quiere Bloquear este recurso?'); ?></p>
                <p class="textMessage hide"></p>

                <p class="link-edukia"></p>

            </div>

            <div class="modal-footer">
                <div class="text-center">
                        <button
                            class="btn btn-danger"
                            id="locked"
                            ><?php echo $this->translate('[es] Bloquear'); ?></button>
                        <button
                            class="btn btn-danger"
                            id="unlocked"
                            ><?php echo $this->translate('[es] Salir'); ?></button>
                    </div>
            </div>

        </div>

    </div>

</div>