<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="4">
                    <a
                        href="<?php echo $this->baseUrl('jakinarazpenak/index/mota/gustoko-berria');?>"
                        title="Gustoko Berria"
                        >Gustoko Berria</a>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php
            $gustokoaMapper = new \Klikasi\Mapper\Sql\Gustokoa();
            foreach ($this->gustokoBerria as $jakinarazpena) {

                $gustokoa = $gustokoaMapper->find($jakinarazpena->getIdKanpotarra());

                $thatUser = $jakinarazpena->getThatUser();
                $zendDate = $jakinarazpena->getSortzeData(true);
                $zendDate->setTimezone('Europe/Madrid');
                
                $trClass = '';

                if ($jakinarazpena->getEgoera() == 'onartua') {
                    $trClass = ' success';
                } elseif ($jakinarazpena->getEgoera() == 'ezOnartua') {
                    $trClass = ' danger';
                }

                ?>
                <tr
                    class="<?php echo $jakinarazpena->getIkusita() == 0 ? 'isNew' : 'isView'; echo $trClass; ?>"
                    data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                    >
                    <td class="izena-thatUser" data-thatUser="<?php echo $thatUser->getId(); ?>">
                        <a
                            href="<?php echo $thatUser->urlProfile(); ?>"
                            title="<?php echo $thatUser->getCompletName(); ?>"
                            ><?php echo $this->ErabiltzaileIrudia($thatUser, 22, true);?>  <?php echo $thatUser->getCompletName(); ?></a>
                    </td>
                    <td>
                        <?php
                        if ($gustokoa) {
                        ?>
                        <a
                            href="<?php echo $gustokoa->getEdukia()->edukiaUrl(); ?>"
                            title="<?php echo $gustokoa->getEdukia()->getTitulua(); ?>"
                            ><?php echo $gustokoa->getEdukia()->getTitulua(); ?> <i class="fa fa-external-link"></i></a>
                        <?php
                        } //end if $gustokoa
                        ?>
                    </td>
                    <td>
                        <?php echo $zendDate->toString("y'eko' MMMM'ren' dd'a' HH:mm:ss", "eu"); ?>
                    </td>
                    <td>
                        <button
                            data-action="viewContent"
                            data-instance="gustokoBerria"
                            data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                            class="btn btn-default"
                            title="<?php echo $this->translate('[es] Ver Contenido'); ?>"
                            ><i class="fa fa-external-link" style="position: static;"></i></button>
                        <button
                            data-action="deleteNotification"
                            data-instance="gustokoBerria"
                            data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                            class="btn btn-default"
                            title="<?php echo $this->translate('[es] Eliminar Notificación');?>"
                            ><i class="fa fa-trash-o" style="position: static;"></i></button>
                        <?php
                        if ($jakinarazpena->getIkusita() == 0) {
                            ?>
                            <button
                                data-action="markView"
                                data-instance="gustokoBerria"
                                data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Marcar como vista'); ?>"
                                ><i class="fa fa-eye" style="position: static;"></i></button>
                            <?php
                        }
                        ?>
                    </td>
                </tr>
                <?php
            }
        ?>
        </tbody>
    </table>
</div>