<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="5">
                    <a
                        href="<?php echo $this->baseUrl('jakinarazpenak/index/mota/ikasle-eskaera/');?>"
                        title="Ikasle Eskaera"
                        >Ikasle Eskaera</a>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->ikasleEskaera as $jakinarazpena) {

                $thatUser = $jakinarazpena->getThatUser();
                $zendDate = $jakinarazpena->getSortzeData(true);
                $zendDate->setTimezone('Europe/Madrid');
                
                $trClass = '';

                if ($jakinarazpena->getEgoera() == 'onartua') {
                    $trClass = ' success';
                } elseif ($jakinarazpena->getEgoera() == 'ezOnartua') {
                    $trClass = ' danger';
                }

                ?>
                <tr
                    class="<?php echo $jakinarazpena->getIkusita() == 0 ? 'isNew' : 'isView'; echo $trClass; ?>"
                    data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                    >
                    <td class="izena-thatUser" data-thatUser="<?php echo $thatUser->getId(); ?>">
                        <a
                            href="<?php echo $thatUser->urlProfile(); ?>"
                            title="<?php echo $thatUser->getCompletName(); ?>"
                            ><?php echo $this->ErabiltzaileIrudia($thatUser, 22, true);?>  <?php echo $thatUser->getCompletName(); ?></a>
                    </td>
                    <td>
                        <?php
                        $ikastegia = new \Klikasi\Mapper\Sql\Ikastegia();
                        $ikastegia = $ikastegia->find($jakinarazpena->getIdKanpotarra());
                        ?>
                        <a
                            href="<?php echo $ikastegia->ikastegiaUrl(); ?>"
                            title="<?php echo $ikastegia->getIzena(); ?>"
                            ><?php echo $ikastegia->getIzena(); ?> <i class="fa fa-external-link"></i></a>
                    </td>
                    <td>
                        <?php echo $zendDate->toString("y'eko' MMMM'ren' dd'a' HH:mm:ss", "eu"); ?>
                    </td>
                    <td>
                        <?php echo ucfirst(strtolower($jakinarazpena->getEgoera())); ?>
                    </td>
                    <td>
                        <?php
                        if ($jakinarazpena->getEgoera() == 'onartzeko') {
                            ?>
                            <button
                                data-action="accept"
                                data-instance="ikasleEskaera"
                                data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Aceptar'); ?>"
                                ><i class="fa fa-thumbs-o-up" style="position: static;"></i></button>
                            <button
                                data-action="reject"
                                data-instance="ikasleEskaera"
                                data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Rechazar'); ?>"
                                ><i class="fa fa-thumbs-o-down" style="position: static;"></i></button>
                            <?php
                        }
                        ?>
                        <button
                            data-action="viewContent"
                            data-instance="ikasleEskaera"
                            data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                            class="btn btn-default"
                            title="<?php echo $this->translate('[es] Ver Contenido'); ?>"
                            ><i class="fa fa-external-link" style="position: static;"></i></button>
                        <button
                            data-action="deleteNotification"
                            data-instance="ikasleEskaera"
                            data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                            class="btn btn-default"
                            title="<?php echo $this->translate('[es] Eliminar Notificación');?>"
                            ><i class="fa fa-trash-o" style="position: static;"></i></button>
                        <?php
                        if ($jakinarazpena->getIkusita() == 0) {
                            ?>
                            <button
                                data-action="markView"
                                data-instance="ikasleEskaera"
                                data-jakinarazpena="<?php echo $jakinarazpena->getId(); ?>"
                                class="btn btn-default"
                                title="<?php echo $this->translate('[es] Marcar como vista'); ?>"
                                ><i class="fa fa-eye" style="position: static;"></i></button>
                            <?php
                        }
                        ?>
                    </td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
</div>