<div class="modal" id="jakinarazpenakDialog">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">
                <h4><?php echo $this->translate('[es] contactar con'); ?>: <em></em></h4>
            </div>

            <div class="modal-body">

                <form
                    class="form-horizontal"
                    role="form"
                    method="POST"
                    id="sendMessage-Form"
                    data-url=""
                    autocomplete="off"
                    >

                    <div id="alert" class="alert hide"></div>

                    <div class="form-group col-xs-12">
                        <p class="kexa-text"></p>
                    </div>

                    <div class="form-group">

                        <label for="message" class="col-sm-2 control-label">Mezua</label>

                        <div class="col-sm-10">
                            <textarea
                                name="message"
                                id="message"
                                class="form-control"
                                placeholder="Mensaje"
                                rows="4"
                                ></textarea>
                                <span class="help-block hide"><?php echo $this->translate('[es] Este mensaje va al email personal.'); ?></span>
                        </div>

                    </div>

                    <div class="form-group col-xs-12 text-center loading-sendMessage hide">
                        <i class="fa fa-refresh fa-spin fa-2x"></i>
                    </div>

                    <input
                        type="hidden"
                        name="jakinarazpenakId"
                        id="jakinarazpenakId"
                        value=""
                        />

                    <input
                        type="hidden"
                        name="erabiltzaileaPosta"
                        id="erabiltzaileaPosta"
                        value=""
                        />

                    <input
                        type="hidden"
                        name="actionInstance"
                        id="actionInstance"
                        value=""
                        />

                    <div class="messageLoading"></div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button
                                class="btn btn-success"
                                id="send"
                                >Bidali</button>
                            <button
                                class="btn btn-danger"
                                id="close"
                                >Itxi</button>
                        </div>
                    </div>

                </form>

            </div>

        </div>

    </div>

</div>