<form class="form-horizontal col-sm-8 col-sm-offset-2" method="POST" action="" autocomplete="off">

    <div class="form-group">

        <div class="form-group">

            <div class="col-sm-12">
                <input
                    type="text"
                    name="erabiltzailea"
                    id="erabiltzailea"
                    class="form-control"
                    autocomplete="off"
                    autofocus="autofocus"
                    placeholder="Erabiltzailea/Posta elektronikoko helbidea"
                    required="required"
                    />
            </div>

        </div>

    </div>

    <div class="form-group">
        <div class="text-center">
            <input type="submit" name="bidali" id="bidali" value="Bidali" class="btn btn-success">
        </div>
    </div>

</form>