<form class="form-horizontal col-sm-8 col-sm-offset-2" method="POST" action="" autocomplete="off">

    <div class="form-group">

        <div class="form-group">

            <label for="pasahitza" class="col-sm-3 control-label">Pasahitza</label>

            <div class="col-sm-9">
                <input
                    type="password"
                    class="form-control"
                    id="pasahitza"
                    name="pasahitza"
                    placeholder="Pasahitza"
                    autofocus="autofocus"
                    required="required"
                    value=""
                    />
            </div>

        </div>

        <div class="form-group">

            <label for="pasahitzaBaieztatu" class="col-sm-3 control-label">Pasahitza baieztatu</label>

            <div class="col-sm-9">
                <input
                    type="password"
                    class="form-control"
                    id="pasahitzaBaieztatu"
                    name="pasahitzaBaieztatu"
                    placeholder="Pasahitza baieztatu"
                    required="required"
                    value=""
                    />
            </div>

        </div>

    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <input type="submit" name="bidali" id="bidali" value="Bidali" class="btn btn-success">
        </div>
    </div>

</form>