<div class="modal" id="{{type}}-dialog">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h2>{{title}}</h2>
            </div>

            <div class="modal-body">

                <form
                    class="form-horizontal"
                    role="form"
                    method="POST"
                    autocomplete="off"
                    >

                    <div class="form-group">
                        <div id="magic-{{type}}"></div>
                    </div>

                    <div class="form-group">

                        <label for="{{type}}" class="col-sm-3 control-label">{{description}}</label>

                        <div class="col-sm-9">
                            <textarea
                                name="{{type}}"
                                id="{{type}}"
                                placeholder="{{description}}"
                                class="form-control"
                                rows="5"
                                cols="40"
                                ></textarea>
                        </div>


                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                            <button
                                class="btn btn-success"
                                id="{{type}}"
                                data-edukia="{{edukiaId}}"
                                data-url="{{urlAction}}?format=json"
                                >Bidali</button>

                            <button
                                id="dialogClosed"
                                class="btn btn-danger"
                                >Itxi</button>
                        </div>
                    </div>

                </form>

            </div>

        </div>
    </div>
</div>