<?php
echo $this->render("header.phtml");
?>
<body>

<?php echo $this->render("menua.phtml"); ?>

<div class="container principal">

    <div class="col-xs-12 subheader bg-standard-grey">
        <?php
        if (isset($this->titleLink)) {
            ?>
            <h1><a
                    href="<?php echo $this->baseUrl($this->titleLink); ?>"
                    title="<?php echo $this->title; ?>"
                    ><?php echo $this->title; ?></a></h1>
            <?php
        } else {
            ?>
            <h1><?php echo $this->title; ?></h1>
            <?php
        }
        ?>
    </div>

    <?php echo $this->layout()->content; ?>

</div>

    <?php echo $this->render("footer.phtml"); ?>

</body>
</html>
