<!doctype html>
<html
    xmlns="http://www.w3.org/1999/xhtml"
    lang="eu"
    class="js flexbox flexboxlegacy canvas canvastext webgl touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths js flexbox flexboxlegacy canvas canvastext webgl touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths">
<head>
    <style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide{display:none !important;}ng\:form{display:block;}.ng-animate-block-transitions{transition:0s all!important;-webkit-transition:0s all!important;}.ng-hide-add-active,.ng-hide-remove{display:block!important;}</style>

    <link rel="shortcut icon" href="<?php echo $this->serverUrl($this->baseUrl('/img/favicon.png'))?>">

    <title><?php echo $this->title;?></title>

    <link rel="canonical" href="<?php echo $this->currentUrl; ?>" />
    <link rel="alternate" hreflang="eu-ES" href="<?php echo $this->currentUrl; ?>" />

    <link rel="alternate" type="application/rss+xml" title="RSS" href="http://www.klikasi.eus/rss/" />

    <!-- Charset usado en la web -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="language" content="basque" />
    <meta http-equiv="content-language" content="eu-ES" />
    <meta property="og:locale" content="eu_ES" />

    <!-- Metas de información general -->
<?php
    if (isset($this->metaTitle)) {
?>
    <meta name="title"       content="<?php echo $this->metaTitle;?>" />
<?php
    }
    
    if (isset($this->metaKeywords)) {
?>
    <meta name="keywords"    content="<?php echo $this->metaKeywords;?>" />
<?php
    }
    
    if (isset($this->metaDescription)) {
?>
    <meta name="description" content="<?php echo $this->metaDescription;?>" />
<?php
    }
?>

    <!-- Metas para Google/Facebook -->
    <!-- Nombre de la Web -->
    <meta property="og:site_name"   content="klikasi" />
    
<?php
    if (isset($this->title)) {
?>
    <meta property="og:title"       content="<?php echo $this->title;?>" />
<?php
    }

    if (isset($this->metaDescription)) {
?>
    <meta property="og:description" content="<?php echo $this->metaDescription;?>" />
<?php
    }

    //<!-- Current URL -->
    if (isset($this->currentUrl)) {
?>
    <meta property="og:url"         content="<?php echo $this->currentUrl;?>" />
<?php
    }

    //<!-- type = article/website/blog/product -->
    if (isset($this->metaType)) {
?>
    <meta property="og:type"        content="<?php echo $this->metaType;?>" />
<?php
    }
?>
    
    <!-- Facebook: Standards vary, but an image at least 200x200px works best. Facebook recommends large images up to 1200x630px wide. -->
<?php
    if (isset($this->urlMetaImage)) {
?>
    <meta property="og:image" content="<?php echo $this->serverUrl($this->urlMetaImage);?>" />
<?php
	}
	

    if ($this->metaType === 'article') {

        if (isset($this->publishedDate)) {
?>
    <meta property="article:published_time" content="<?php echo $this->publishedDate;?>" />
<?php 
        }
        
        if (isset($this->modifiedDate)) {
?>
    <meta property="article:modified_time" content="<?php echo $this->modifiedDate;?>" />
<?php
        }
        
        if (isset($this->category)) {
?>
    <meta property="article:section" content="<?php echo $this->category;?>" />
<?php
        }

        if (isset($this->tag)) {
?>
    <meta property="article:tag" content="<?php echo $this->tag;?>" />
<?php
        }
    }
?>

    <!-- Metas para Twitter -->
    <!--  title:       maximo 70 caracteres  -->
    <!--  description: maximo 200 caracteres  -->
    <!--  image: imagenes de 1MB  -->

    <!-- cuenta de portal @web -->
    <meta name="twitter:site" content="@azkuefundazioa" />

    <!-- Url actual -->
    <meta name="twitter:url" content="<?php echo $this->currentUrl; ?>" />
    <meta name="twitter:title" content="<?php echo $this->title; ?>" />
    <meta name="twitter:description" content="<?php echo $this->metaDescription; ?>" />

    <!--  summary  -->
    <!--  image: 120x120 proporcion 4:3  -->
    <meta name="twitter:card" content="summary" />
<?php
    if (isset($this->urlMetaImage)) {
?>
    <meta name="twitter:image" content="<?php echo $this->serverUrl($this->urlMetaImage);?>" />
<?php
	}
?>

<!-- Para que los navegadores adapten el contenido -->
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-54471895-1', 'auto');
          ga('send', 'pageview');
        </script>
    <?php

    echo $this->metaDatadaSocials($this->isSocial);

    echo $this->headLink()
        ->appendStylesheet($this->baseUrl('/styles/main.min.css'), array('screen', 'projection'))
        ->appendStylesheet($this->baseUrl('/bower/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'))
        ->appendStylesheet($this->baseUrl('/bower/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'))
        ->appendStylesheet($this->baseUrl('/bower/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'))
        ->setIndent(4);
        ?>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <base href="<?php echo $this->serverUrl($this->baseUrl("/")); ?>" />
    <script type="text/javascript">

        window.custonScreenMatch = false;
        if (window.matchMedia) {
            window.custonScreenMatch = window.matchMedia("screen and (max-width: 765px)");
        }

    </script>

</head>