<!-- header.hbs -->
<header>
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Menú superior login -->

            <nav id="header-login" role="navigation">
                <span class="border-bottom">
                    <ul class="nav navbar-nav list-inline pull-right">
                        <?php echo $this->ErabiltzaileMenua(); ?>
                    </ul>
                </span>
            </nav>

            <nav class="navbar-header" role="navigation">
                <a class="navbar-brand" href="" title="Klikasi">
                    <img class="" src="images/logo_klikasi.png" alt="Klikasi. Sortu. Partekatu. Ikasi.">
                    <!-- <img class="visible-xs" src="images/logo_klikasi_mobile.png" alt="Klikasi. Sortu. Partekatu. Ikasi."> -->
                </a>

                <ul id="header-social" class="nav navbar-nav list-inline pull-right">
                    <li>
                        <a
                            href="http://www.azkuefundazioa.org"
                            target="_blank"
                            class="azkue"
                            >Azkue Fundazioa</a>
                    </li>

                    <li>
                        <a href="https://twitter.com/AzkueFundazioa/" target="_blank" class="twitter" title="Twitter azkue fundazioa">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/AzkueFundazioa/" target="_blank" class="facebook" title="Facebook azkue fundazioa">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.pinterest.com/azkuefundazioa/" target="_blank" class="pinterest" title="pinterest azkue fundazioa">
                            <i class="fa fa-pinterest"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/user/AzkueFundazioa/" target="_blank" class="youtube" title="youtube azkue fundazioa">
                            <i class="fa fa-youtube"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.diigo.com/user/AzkueFundazioa/" target="_blank" class="diigo" title="Diigo azkue fundazioa">Diigo</a>
                    </li>
                    <li>
                        <a href="http://www.azkuefundazioarenegunkaria.org/" target="_blank" class="blog">Bloga</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->baseUrl('/rss'); ?>" title="RSS"class="rss"><i class="fa fa-rss"></i></a>
                    </li>
                </ul>
            </nav>

            <?php
                echo $this->render('menu-big.phtml');
                //echo $this->render('menu-small.phtml');
            ?>

        </div><!-- END .container -->
    </div><!-- END role="navigation" -->
</header>
<div id = 'loader' class="page-loader center-align">
            <ul class="be-loader">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>       
</div>
<div id = 'main-content'>  