<!doctype html>
<html
    xmlns="http://www.w3.org/1999/xhtml"
    lang="eu"
    class="js flexbox flexboxlegacy canvas canvastext webgl touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths js flexbox flexboxlegacy canvas canvastext webgl touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths">
<head>

    <title><?php echo $this->title; ?></title>

    <link rel="shortcut icon" href="<?php echo $this->serverUrl($this->baseUrl('/img/favicon.png'))?>">

    <meta name="viewport" content="width=device-width" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <base href="<?php echo $this->serverUrl($this->baseUrl("/")); ?>" />
    <style type="text/css">
        a {text-decoration: none; color: #369 !important;}
        a:ACTIVE {color: #369 !important;}
        a:HOVER {color: #369 !important;}
        a:FOCUS {color: #369 !important;}
    </style>
</head>


<?php
    echo $this->layout()->content;
?>