<?php
$edukia = $this->edukia;
?>
<form
    role="form"
    class="form-horizontal edukiak-igo"
    method="POST"
    autocomplete="off"
    >

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 pull-left">

                <input
                    type="hidden"
                    name="edukia-id"
                    value="<?php echo $edukia->getId(); ?>">

                <div class="element-group">
                    <input
                        type="text"
                        name="titulua"
                        class="col-xs-12 form-control"
                        id="titulua"
                        placeholder="Izenburua"
                        autofocus="autofocus"
                        value="<?php echo $edukia->getTitulua(); ?>"
                        />
                </div>
                <div class="element-group select2">
                    <span class="select form-control"><i class="fa fa-chevron-down"></i>
                        <select
                            multiple
                            class="form-control"
                            id="kategoriak"
                            name="kategoriak[]"
                            >
                            <?php
                            foreach ($this->kategoriakGlobala as $key => $val) {
                                ?>
                                <optgroup label="<?php echo $key; ?>">
                                <?php
                                foreach ($val as $kategoria) {
                                        $selected = in_array($kategoria->getId(), $this->currentKategoriak) ? 'selected' : '';
                                    ?>
                                    <option <?php echo $selected; ?>
                                        value="<?php echo $kategoria->getId(); ?>"
                                        ><?php echo $kategoria->getIzena(); ?></option>
                                    <?php
                                }
                                ?>
                                </optgroup>
                                <?php
                            }
                            ?>
                        </select>
                    </span>
                </div>

                <div class="row">

                    <div class="col-xs-12 col-md-6 pull-left">
                        <div class="element-group">
                            <span class="select"><i class="fa fa-chevron-down"></i>
                                <select
                                    class="form-control"
                                    id="maila"
                                    name="maila"
                                    data-selected="<?php echo $this->currentMaila;?>"
                                    >
                                    <?php
                                    foreach ($this->mailak as $maila) {
                                        ?>
                                        <option
                                            value="<?php echo $maila->getId(); ?>"
                                            ><?php echo $maila->getIzena(); ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </span>
                        </div>
                    </div><!-- .col-xs-12.col-md-6.pull-left -->

                    <div class="col-xs-12 col-md-6 pull-right">

                        <div class="adina col-xs-12">

                            <label class="col-xs-1" for="adina">Adina</label>
                            <span class="sel-edad col-xs-11">

                                <span class="edad-min" data-toggle="tooltip" data-original-title="Default tooltip">
                                    <a>
                                        <span class="edad"><strong class="min-years">10</strong> urtetik</span>
                                    </a>
                                </span>
                                <span class="edad-max" data-toggle="tooltip" data-original-title="Default tooltip">
                                    <a>
                                        <span class="edad"><strong class="max-years">45</strong> urtera</span>
                                    </a>
                                </span>

                                <input
                                    type="text"
                                    name="adina"
                                    value="<?php echo $edukia->getUrteakNoiztik() . ',' . $edukia->getUrteakNoizarte()?>"
                                    data-slider-min="0"
                                    data-slider-max="100"
                                    data-slider-step="1"
                                    data-slider-value="[<?php echo $edukia->getUrteakNoiztik() . ',' . $edukia->getUrteakNoizarte()?>]"
                                    data-selected="true"
                                    id="adina"
                                    />
                            </span><!-- .sel-edad.col-xs-12 -->

                        </div><!-- .adina -->
                    </div><!-- .col-xs-12.col-md-6.pull-right -->

                </div><!-- .row -->

                <div class="element-group">
                    <textarea
                        name="deskribapenLaburra"
                        id="deskribapenLaburra"
                        class="form-control"
                        rows="3"
                        placeholder="Laburpena"
                        ><?php echo $edukia->getDeskribapenLaburra(); ?></textarea>

                    <span class="help-block">Labur itzazu <span class="countCharactes"></span> karakteretan baliabidearen gaia.</span>

                </div>

                <div class="element-group">
                    <textarea
                        name="deskribapena"
                        id="deskribapena"
                        class="form-control"
                        rows="8"
                        placeholder="Deskribapena"
                        ><?php echo $edukia->getDeskribapena(); ?></textarea>
                </div>

            </div><!-- .col-xs-12.col-sm-6.pull-left -->

            <div class="col-xs-12 col-sm-5">

                <div class="element-group">
                    <input
                        class="form-control"
                        id="disabledInput"
                        type="text"
                        placeholder="Nire izena"
                        value="<?php echo $edukia->getUrl(); ?>"
                        disabled
                        />
                </div>

                <div class="element-group">
                    <span class="select"><i class="fa fa-chevron-down"></i>
                        <select
                            class="form-control"
                            id="eskola"
                            name="eskola"
                            data-selected="<?php echo $this->currentEskola; ?>"
                            >
                            <option></option>
                            <?php
                            foreach ($this->eskolak as $eskola) {
                                ?>
                                <option
                                    value="<?php echo $eskola->getId(); ?>"
                                    ><?php echo $eskola->getIzena() . ', ' . $eskola->getHerria(); ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </span>
                </div>

                <div class="beste-egile-content">
                    <input
                        type="text"
                        name="beste-egile"
                        id="beste-egile"
                        class=""
                        autocomplete="off"
                        autocorrect="off"
                        autocapitalize="off"
                        spellcheck="false"
                        tabindex="0"
                        placeholder="Lankideen izenak"
                        style="width: 100%;"
                        data-selected="<?php echo implode(',', $this->currentKolaboratzaileak); ?>"
                        />

                        <span class="help-block col-xs-12">Komekin banatu.</span>
                </div>

                <div class="beste-egile-etiketak">

                    <input
                        type="text"
                        name="etiketak"
                        id="etiketak"
                        class=""
                        autocomplete="off"
                        autocorrect="off"
                        autocapitalize="off"
                        spellcheck="false"
                        tabindex="0"
                        placeholder="Etiketak"
                        style="width: 100%;"
                        data-selected="<?php echo implode(',', $this->currentEtiketak); ?>"
                        />

                        <span class="help-block col-xs-12">Komekin banatu.</span>
                </div>

                <div class="element-group select2">
                    <?php
                    if (! empty($this->kanpainaKodeak)) {
                    ?>
                    <select multiple class="form-control" id="kanpaina" name="kanpaina[]">
                    <?php
                    foreach ($this->kanpainaKodeak as $id => $name) {

                        $selected = in_array($id, $this->selectedKanpainaKodeak) ? 'selected' : '';
                        echo '<option '.$selected.' value="'. $id .'">'. $name .'</option>';
                    }
                    ?>
                    </select>
                    <?php
                    } //end if
                    ?>
                </div>

            </div><!-- .col-xs-12.col-sm-6 -->

        </div><!-- .row -->
    </div><!-- .container -->

    <?php
        echo $this->partial("edukiak-igo/baliabideak.phtml", array("edukia" => $this->edukia));
    ?>

    <div class="container">
        <div class="row checkbox">
            <span class="col-xs-12">
                <label>
                    <input type="checkbox" name="acceptConditions" />
                    <p>
                        <a
                            href="<?php echo $this->baseUrl('orriak/zerbitzu-baldintzak/'); ?>"
                            title="Zerbitzu baldintzak"
                            >Zerbitzu baldintzak</a> eta <a
                                                            href="<?php echo $this->baseUrl('orriak/lizentzia/'); ?>"
                                                            title="Lizentzia"
                                                            > Lizentzia</a> irakurri ditut eta ados nago.
                    </p>
                </label>
            </span>
        </div>

        <span class="row text-center">
            <span class="col-sm-12">
                <div class="col-sm-5">
                    <button id="datuak-save" class="btn-bidali bg-green light">Bidali</button>
                </div>
                <div class="col-sm-5 col-sm-offset-1">
                    <button id="datuak-utzi" class="btn-bidali bg-red light">Utzi</button>
                </div>

            </span>
        </span>
        <div class="row">
            <div class="color-border"></div>
        </div>
    </div>

    <div class="container">

        <button
            type="button"
            class="btn btn-danger"
            id="showDeletePost"
            ><?php echo  $this->translate('[es] Eliminar Recurso');?></button>

        <div
            class="alert alert-danger fade in hide"
            id="confirmationDeletePostMessage"
            role="alert">
            <p><?php echo $this->translate('[es] mensaje de advertencia, sobre la eliminación del recurso actual. '); ?></p>
            <p>
                <button
                    type="button"
                    class="btn btn-danger"
                    id="confirmationDeletePostButton"
                    ><?php echo  $this->translate('[es] Si, Eliminar este recurso');?></button>
            </p>
        </div>
    </div>

</form>