<?php
$where = array(
    'edukiaId = ?' => $this->edukia->getId()
);
$order = array(
    'sortzeData DESC'
);

$hobekuntzakList = new \Klikasi\Mapper\Sql\Hobekuntzak();
$hobekuntzakList = $hobekuntzakList->fetchList($where, $order);
?>

<div id="nire-laguntzaileak">
    <div class="form-group">
        <h2>Hobekuntzak</h2>

        <div class="col-xs-12" id="hobekuntzak">
            <?php
            $noMoreHobekuntzak = true;
                if (!empty($hobekuntzakList)) {
                    $noMoreHobekuntzak = false;
                    foreach ($hobekuntzakList as $hobekuntzak) {
                        $erabiltzailea = $hobekuntzak->getErabiltzailea();
                        ?>
                        <div class="row notificationCustomRow" data-relation="<?php echo $hobekuntzak->getId(); ?>">
                            <div class="row">
                                <div class="col-xs-6 col-sm-6 pull-left">
                                    <a
                                        href="<?php echo $this->baseUrl('erabiltzaileak/ikusi/erabiltzailea/' . $erabiltzailea->getUrl()); ?>"
                                        title="<?php echo $erabiltzailea->getCompletName(); ?>"
                                        ><?php echo $this->ErabiltzaileIrudia($erabiltzailea, 22, true); ?> <?php echo $erabiltzailea->getCompletName(); ?></a>
                                </div>
                                <div class="col-xs-6 col-sm-6 pull-right text-right">
                                    <small><?php echo $hobekuntzak->getSortzeData(); ?></small>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-12">
                                    <p><?php echo $hobekuntzak->getHobekuntzak(); ?></p>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-xs-6 col-sm-6 pull-left hobekuntzakModerationStatus"></div>

                                <div class="col-xs-6 col-sm-6 pull-right text-right">

                                    <button
                                        data-action="replyHobekuntzak"
                                        data-relation="<?php echo $hobekuntzak->getId(); ?>"
                                        class="btn btn-default"
                                        title="<?php echo $this->translate('[es] Responder'); ?>"
                                        ><i class="fa fa-envelope-o" style="position: static;"></i></button>

                                    <button
                                        data-action="deleteHobekuntzak"
                                        data-relation="<?php echo $hobekuntzak->getId(); ?>"
                                        class="btn btn-default"
                                        title="<?php echo $this->translate('[es] Eliminar'); ?>"
                                        ><i class="fa fa-trash-o text-danger" style="position: static;"></i></button>

                                </div>
                            </div>

                        </div>
                        <?php
                    }
                }
            ?>
            <div class="col-xs-12 noMoreHobekuntzak <?php echo (!$noMoreHobekuntzak ? 'hide' : '') ?>" >
                <p><?php echo $this->translate('[es] No hay Hobekuntzak'); ?></p>
            </div>

        </div>
    </div>
</div>