<span class="col-xs-12 col-sm-6">
    <span class="row externalElement">
        <span class="col-xs-9 col-sm-10 col-md-10 col-lg-11">
            <div class="input-group balibide-input">
                <span class="input-group-addon"><i class="fa fa-{{icon}}"></i></span>
                <input type="text" name="{{name}}[]" value="{{value}}" class="form-control" placeholder="http://..." />
            </div>
        </span>

        <span class="col-xs-3 col-sm-2 col-md-2 col-lg-1 externalAction">
            <button class="pull-right btn btn-default btn-plus"><i class="fa fa-plus"></i></button>
        </span>
    </span>
</span>