production: 
  class: \Klikasi\Model\AtseginDut
  fields: 
    edukiaId: 
      title: _('Edukia id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Edukia
          fieldName: 
            fields: 
              - titulua
            template: '%titulua%'
          order: titulua
      default: true
    erabiltzaileaId: 
      title: _('Erabiltzailea id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
