production: 
  class: \Klikasi\Model\EdukiaRelIkastegia
  fields: 
    EdukiaId: 
      title: _('Edukia id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Edukia
          fieldName: 
            fields: 
              - titulua
            template: '%titulua%'
          order: titulua
      default: true
    ikastegiaId: 
      title: _('Ikastegia')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Ikastegia
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      decorators:
        autocomplete:
          command: autocompleteIkastegia_command
    egoera: 
      title: _('Egoera')
      type: select
      defaultValue: onartzeko
      source: 
        data: inline
        values: 
          'onartzeko': _('Onartzeko zain')
          'onartua': _('Onartua')
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
