production: 
  class: \Klikasi\Model\EmailHistory
  fields: 
    erabiltzaileaId: 
      title: _('Erabiltzailea id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
    type: 
      title: _('Type')
      type: select
      required: true
      source: 
        data: inline
        values: 
          'jakinarazpenak': _('jakinarazpenak')
          'izena-eman': _('izena-eman')
          'pasahitza-berreskuratu': _('pasahitza-berreskuratu')
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
