production: 
  class: \Klikasi\Model\ErabiltzaileaRelIkastegia
  fields: 
    erabiltzaileaId: 
      title: _('Erabiltzailea')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
      decorators:
        autocomplete:
          command: autocompleteErabiltzailea_command
    ikastegiaId: 
      title: _('Ikastegia id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Ikastegia
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    administratzailea: 
      title: _('Administratzailea')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("Ez")
          '1': 
            title: _("Bai")
    jabea: 
      title: _('Jabea')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("Ez")
          '1': 
            title: _("Bai")
    egoera: 
      title: _('Egoera')
      type: select
      defaultValue: onartzeko
      source: 
        data: inline
        values: 
          'onartzeko': _('Onartzeko zain')
          'onartua': _('Onartua')
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
