production: 
  class: \Klikasi\Model\Esteka
  fields: 
    
    titulua: 
      title: _('Titulua')
      type: text
    
    url: 
      title: _('Url')
      type: html5
      source:
        control: url
      required: true
      
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production