production: 
  class: \Klikasi\Model\HomePage
  fields: 
    identifier: 
      title: _('Identifier')
      type: text
      required: true
      default: true
    title: 
      title: _('Title')
      type: text
      required: true
    description: 
      title: _('Description')
      type: textarea
    irudia: 
      title: _('Irudia')
      type: file
      source: 
        data: fso
        size_limit: 20M
        options: 
          download: 
            external: true
            type: command
            target: IrudiaDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          upload: 
            type: command
            target: IrudiaUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          preview: 
            target: IrudiaPreview_command
            type: command
            class: filePreview
            external: 1
            props: 
              width: 150
              height: 150
              crop: false
            onNull: hide
          previewList: 
            target: IrudiaPreview_command
            type: command
            class: filePreview
            listController: 1
            external: 1
            props: 
              width: 30
              height: 30
              crop: false
            onNull: hide
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
