production: 
  class: \Klikasi\Model\Ikastegia
  fields: 
    izena: 
      title: _('Izena')
      type: text
      required: true
      default: true
    deskribapenLaburra: 
      title: _('Deskribapen laburra')
      type: textarea
      required: true
    deskribapena: 
      title: _('Deskribapena')
      type: textarea
      source:
        control: Tinymce
        template: html5
    herria: 
      title: _('Herria')
      type: text
      required: true
    probintzia: 
      title: _('Probintzia')
      type: text
      required: true
    kokapena: 
      title: _('Kokapena')
      type: map
      required: true
    kokapenaLat: 
      title: _('Kokapena lat')
      type: text
      required: true
    kokapenaLng: 
      title: _('Kokapena lng')
      type: text
      required: true
    mota: 
      title: _('Mota')
      type: select
      defaultValue: ikastegia
      source: 
        data: inline
        values: 
          'ikastetxea': _('Ikastetxea')
          'bestelakoa': _('Bestelakoa')
    irudia: 
      title: _('Irudia')
      type: file
      source: 
        data: fso
        size_limit: 20M
        options: 
          hiddenName: true 
          download: 
            external: true
            type: command
            target: IrudiaDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          upload: 
            type: command
            target: IrudiaUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          preview: 
            target: IrudiaPreview_command
            type: command
            class: filePreview
            external: 1
            props: 
              height: 200
            crop: 1
            onNull: hide
          previewList: 
            target: IrudiaPreview_command
            type: command
            class: filePreview
            listController: 1
            external: 1
            props: 
              height: 90
            crop: 1
            onNull: hide
    aktibatua: 
      title: _('Aktibatua')
      type: checkbox
      defaultValue: 0
    linkedin: 
      title: _('Linkedin')
      type: text
    facebook: 
      title: _('Facebook')
      type: text
    twitter: 
      title: _('Twitter')
      type: text
    google: 
      title: _('Google')
      type: text
    youtube: 
      title: _('Youtube')
      type: text
    instagram: 
      title: _('Instagram')
      type: text
    pinterest: 
      title: _('Pinterest')
      type: text
    url: 
      title: _('Url')
      type: text
      required: true
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'

    ikasleKopurua:
      title: _('Ikasle kopurua')
      type: text


    edukiKopurua:
      title: _('Eduki kopurua')
      type: text

    karma:
      title: _('Karma')
      type: text

    IkastegiaRelGaiak: 
      title: _("Ikasgaiak")
      type: multiselect
      source:
        data: mapper
        config:
          relationMapper: \Klikasi\Mapper\Sql\IkastegiaRelGaiak
          relatedMapperName: \Klikasi\Mapper\Sql\IkastegiGaiak
          relatedFieldName: izena
          relationProperty: IkastegiGaiak
      decorators:
        autocomplete:
          command: autocompleteGaia_command
      options:
        screens:
          gaiBerriaExternal_screen: true

    IkastegiaRelMota: 
      title: _("Motak")
      type: multiselect
      source:
        data: mapper
        config:
          relationMapper: \Klikasi\Mapper\Sql\IkastegiaRelMota
          relatedMapperName: \Klikasi\Mapper\Sql\IkastegiMota
          relatedFieldName: izena
          relationProperty: IkastegiMota
      decorators:
        autocomplete:
          command: autocompleteMota_command
      options:
        screens:
          motaBerriaExternal_screen: true

    

testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
