production: 
  class: \Klikasi\Model\IkastegiGaiak
  fields: 
    izena: 
      title: _('Izena')
      type: text
      required: true
      default: true
    url: 
      title: _('Url')
      type: text
      required: true
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
