production: 
  class: \Klikasi\Model\IkastegiaRelMota
  fields: 
    ikastegiaId: 
      title: _('Ikastegia id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Ikastegia
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
    ikastegiMotaId: 
      title: _('Ikastegi mota id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\IkastegiMota
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
