production: 
  class: \Klikasi\Model\Irudia
  fields: 
    
    titulua: 
      title: _('Titulua')
      type: text
      
    url: 
      title: _('Url')
      type: html5
      source:
        control: url
      defaultValue: NULL
      
    fitxategia: 
      title: _('Fitxategia')
      type: file
      defaultValue: NULL
      source: 
        data: fso
        size_limit: 20M
        options: 
          hiddenName: true
          download: 
            external: true
            type: command
            target: IrudiaDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          upload: 
            type: command
            target: IrudiaUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          preview: 
            target: IrudiaPreview_command
            type: command
            class: filePreview
            external: 1
            props: 
              height: 200
            crop: 1
            onNull: hide
          previewList: 
            target: IrudiaPreview_command
            type: command
            class: filePreview
            listController: 1
            external: 1
            props: 
              height: 90
            crop: 1
            onNull: hide
            
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
