production: 
  class: \Klikasi\Model\JakinarazpenakGroup
  fields: 
    jakinarazpenakId: 
      title: _('Jakinarazpenak id')
      type: number
      required: true
      source: 
        control: Spinner
      default: true
    erabiltzaileaId: 
      title: _('Erabiltzailea id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    sortzeData: 
      title: _('Sortze data')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
