production: 
  class: \Klikasi\Model\KanpainaRelIkastegiMota
  fields: 
    kanpainaId: 
      title: _('Kanpaina id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Kanpaina
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
    ikastetxeMotaId: 
      title: _('Ikastegi mota')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\IkastegiMota
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
