production: 
  class: \Klikasi\Model\KategoriakRelKategoriaGlobalak
  fields: 
    kategoriaId: 
      title: _('Kategoria')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Kategoria
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
          filterClass: \Klikasi\Klear\Filter\KategoriaMultzoan
      decorators:
        autocomplete:
          command: autocompleteKategoria_command
      options:
        screens:
          kategoriaBerriaExternal_screen: true
      default: true
    kategoriaGlobalaId: 
      title: _('Kategoria multzoa')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\KategoriaGlobala
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena


testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
