production: 
  class: \Klikasi\Model\Lagunak
  fields: 
    erabiltzaileaId: 
      title: _('Erabiltzailea id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
      default: true
    erabiltzaileaId1: 
      title: _('Erabiltzailea id1')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Klikasi\Mapper\Sql\Erabiltzailea
          fieldName: 
            fields: 
              - izena
            template: '%izena%'
          order: izena
    egoera: 
      title: _('Egoera')
      type: select
      required: true
      source: 
        data: inline
        values: 
          'eskaera': _('eskaera')
          'onartua': _('onartua')
          'ukatua': _('ukatua')
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
