mappers: 
  - &AtseginDut {mapper: \Klikasi\Mapper\Sql\AtseginDut, modelFile: AtseginDut}
  - &Aurkezpena {mapper: \Klikasi\Mapper\Sql\Aurkezpena, modelFile: Aurkezpena}
  - &Bideoa {mapper: \Klikasi\Mapper\Sql\Bideoa, modelFile: Bideoa}
  - &Edukia {mapper: \Klikasi\Mapper\Sql\Edukia, modelFile: Edukia}
  - &EdukiaRelIkastegia {mapper: \Klikasi\Mapper\Sql\EdukiaRelIkastegia, modelFile: EdukiaRelIkastegia}
  - &EdukiaRelKanpaina {mapper: \Klikasi\Mapper\Sql\EdukiaRelKanpaina, modelFile: EdukiaRelKanpaina}
  - &EdukiaRelKategoria {mapper: \Klikasi\Mapper\Sql\EdukiaRelKategoria, modelFile: EdukiaRelKategoria}
  - &EdukiaRelMaila {mapper: \Klikasi\Mapper\Sql\EdukiaRelMaila, modelFile: EdukiaRelMaila}
  - &EmailHistory {mapper: \Klikasi\Mapper\Sql\EmailHistory, modelFile: EmailHistory}
  - &Erabiltzailea {mapper: \Klikasi\Mapper\Sql\Erabiltzailea, modelFile: Erabiltzailea}
  - &ErabiltzaileaRelEdukia {mapper: \Klikasi\Mapper\Sql\ErabiltzaileaRelEdukia, modelFile: ErabiltzaileaRelEdukia}
  - &ErabiltzaileaRelIkastegia {mapper: \Klikasi\Mapper\Sql\ErabiltzaileaRelIkastegia, modelFile: ErabiltzaileaRelIkastegia}
  - &ErabiltzaileaRelIrakaslea {mapper: \Klikasi\Mapper\Sql\ErabiltzaileaRelIrakaslea, modelFile: ErabiltzaileaRelIrakaslea}
  - &ErabiltzaileaSettings {mapper: \Klikasi\Mapper\Sql\ErabiltzaileaSettings, modelFile: ErabiltzaileaSettings}
  - &ErabiltzaileenIrudiak {mapper: \Klikasi\Mapper\Sql\ErabiltzaileenIrudiak, modelFile: ErabiltzaileenIrudiak}
  - &Esteka {mapper: \Klikasi\Mapper\Sql\Esteka, modelFile: Esteka}
  - &EtagVersions {mapper: \Klikasi\Mapper\Sql\EtagVersions, modelFile: EtagVersions}
  - &Etiketa {mapper: \Klikasi\Mapper\Sql\Etiketa, modelFile: Etiketa}
  - &EtiketaRelEdukia {mapper: \Klikasi\Mapper\Sql\EtiketaRelEdukia, modelFile: EtiketaRelEdukia}
  - &Fitxategia {mapper: \Klikasi\Mapper\Sql\Fitxategia, modelFile: Fitxategia}
  - &Gustokoa {mapper: \Klikasi\Mapper\Sql\Gustokoa, modelFile: Gustokoa}
  - &Hobekuntzak {mapper: \Klikasi\Mapper\Sql\Hobekuntzak, modelFile: Hobekuntzak}
  - &HomePage {mapper: \Klikasi\Mapper\Sql\HomePage, modelFile: HomePage}
  - &IkastegiGaiak {mapper: \Klikasi\Mapper\Sql\IkastegiGaiak, modelFile: IkastegiGaiak}
  - &IkastegiMota {mapper: \Klikasi\Mapper\Sql\IkastegiMota, modelFile: IkastegiMota}
  - &Ikastegia {mapper: \Klikasi\Mapper\Sql\Ikastegia, modelFile: Ikastegia}
  - &IkastegiaRelGaiak {mapper: \Klikasi\Mapper\Sql\IkastegiaRelGaiak, modelFile: IkastegiaRelGaiak}
  - &IkastegiaRelMota {mapper: \Klikasi\Mapper\Sql\IkastegiaRelMota, modelFile: IkastegiaRelMota}
  - &Irudia {mapper: \Klikasi\Mapper\Sql\Irudia, modelFile: Irudia}
  - &Iruzkina {mapper: \Klikasi\Mapper\Sql\Iruzkina, modelFile: Iruzkina}
  - &Jakinarazpenak {mapper: \Klikasi\Mapper\Sql\Jakinarazpenak, modelFile: Jakinarazpenak}
  - &JakinarazpenakGroup {mapper: \Klikasi\Mapper\Sql\JakinarazpenakGroup, modelFile: JakinarazpenakGroup}
  - &JakinarazpenakMota {mapper: \Klikasi\Mapper\Sql\JakinarazpenakMota, modelFile: JakinarazpenakMota}
  - &Kanpaina {mapper: \Klikasi\Mapper\Sql\Kanpaina, modelFile: Kanpaina}
  - &KanpainaRelEdukiKategoriak {mapper: \Klikasi\Mapper\Sql\KanpainaRelEdukiKategoriak, modelFile: KanpainaRelEdukiKategoriak}
  - &KanpainaRelIkastegiMota {mapper: \Klikasi\Mapper\Sql\KanpainaRelIkastegiMota, modelFile: KanpainaRelIkastegiMota}
  - &KanpainaRelKategoria {mapper: \Klikasi\Mapper\Sql\KanpainaRelKategoria, modelFile: KanpainaRelKategoria}
  - &Kategoria {mapper: \Klikasi\Mapper\Sql\Kategoria, modelFile: Kategoria}
  - &KategoriaGlobala {mapper: \Klikasi\Mapper\Sql\KategoriaGlobala, modelFile: KategoriaGlobala}
  - &KategoriakRelKategoriaGlobalak {mapper: \Klikasi\Mapper\Sql\KategoriakRelKategoriaGlobalak, modelFile: KategoriakRelKategoriaGlobalak}
  - &Kexa {mapper: \Klikasi\Mapper\Sql\Kexa, modelFile: Kexa}
  - &KlearUsers {mapper: \Klikasi\Mapper\Sql\KlearUsers, modelFile: KlearUsers}
  - &Kontaktua {mapper: \Klikasi\Mapper\Sql\Kontaktua, modelFile: Kontaktua}
  - &Lagunak {mapper: \Klikasi\Mapper\Sql\Lagunak, modelFile: Lagunak}
  - &Laguntza {mapper: \Klikasi\Mapper\Sql\Laguntza, modelFile: Laguntza}
  - &Maila {mapper: \Klikasi\Mapper\Sql\Maila, modelFile: Maila}
  - &Mezuak {mapper: \Klikasi\Mapper\Sql\Mezuak, modelFile: Mezuak}
  - &Newsletter {mapper: \Klikasi\Mapper\Sql\Newsletter, modelFile: Newsletter}
  - &NewsletterHash {mapper: \Klikasi\Mapper\Sql\NewsletterHash, modelFile: NewsletterHash}
  - &Notifikazioa {mapper: \Klikasi\Mapper\Sql\Notifikazioa, modelFile: Notifikazioa}
  - &Orrialdea {mapper: \Klikasi\Mapper\Sql\Orrialdea, modelFile: Orrialdea}
  - &Changelog {mapper: \Klikasi\Mapper\Sql\Changelog, modelFile: Changelog}
  - &Literales {mapper: \Klikasi\Mapper\Sql\Literales, modelFile: Literales}
