<table style="width:100%; margin: 0 auto; padding:8px;">
    <tbody>
        <tr>
            <td colspan="7">
                <a
                    href="{{klikasiUrl}}"
                    title="Klikasi"
                    style="text-decoration: none;"
                    ><img
                        src="{{klikasiUrl}}/images/logo_klikasi.png"
                        alt="Klikasi"
                        /></a>
            </td>
        </tr>
        <tr>
            <td>
                <a
                    href="http://www.azkuefundazioa.org"
                    title="Azkue Fundazioa"
                    target="_blank"
                    ><img
                        src="{{klikasiUrl}}/images/logo_azkue.png"
                        alt="Azkue Fundazioa"
                        /></a>
            </td>
            <td style="width: 50px;text-align: center;">
                <a
                    href="https://twitter.com/AzkueFundazioa/"
                    target="_blank"
                    title="Twitter azkue fundazioa"
                    ><img src="{{klikasiUrl}}/img/fontawesome-png/grey/24/twitter.png" alt="Twitter azkue fundazioa" /></a>
            </td>
            <td style="width: 50px;text-align: center;">
                <a
                    href="https://www.facebook.com/AzkueFundazioa/"
                    target="_blank"
                    title="Facebook azkue fundazioa"
                    ><img src="{{klikasiUrl}}/img/fontawesome-png/grey/24/facebook.png" alt="Facebook azkue fundazioa" /></a>
            </td>
            <td style="width: 50px;text-align: center;">
                <a
                    href="http://www.pinterest.com/azkuefundazioa/"
                    target="_blank"
                    title="Pinterest azkue fundazioa"
                    ><img src="{{klikasiUrl}}/img/fontawesome-png/grey/24/pinterest.png" alt="Pinterest azkue fundazioa" /></a>
            </td>
            <td style="width: 50px;text-align: center;">
                <a
                    href="https://www.youtube.com/user/AzkueFundazioa/"
                    target="_blank"
                    title="Youtube azkue fundazioa"
                    ><img src="{{klikasiUrl}}/img/fontawesome-png/grey/24/youtube.png" alt="Youtube azkue fundazioa" /></a>
            </td>
            <td style="width: 50px;text-align: center;">
                <a
                    href="http://www.azkuefundazioarenegunkaria.org/"
                    target="_blank"
                    title="Bloga azkue fundazioa"
                    style="color: #808080 !important; cursor: auto; border-left: 1px solid #ECECEC;"
                    >Bloga</a>
            </td>
            <td style="width: 50px;text-align: center;">
                <a
                    href="{{klikasiUrl}}/rss"
                    title="RSS"
                    ><img src="{{klikasiUrl}}/img/fontawesome-png/grey/24/rss.png" alt="RSS" /></a>
            </td>
        </tr>
    </tbody>
</table>

<table width="100%" style="font-family:Helvetica,‘Helvetica Neue’,Arial,sans-serif">
    <tbody>
        <tr>
            <td width="98%" align="center">

                    <table width="547" style="font-family:Helvetica,‘Helvetica Neue’,Arial,sans-serif;border:1px solid #cccccc;border-width:0 1px 1px; box-shadow: 1px 3px 11px #949494;"
                        >
                        <tbody>
                            <tr>
                                <td
                                    colspan="3"
                                    >
                                    <table
                                        width="1"
                                        cellspacing="0"
                                        cellpadding="0"
                                        border="0"
                                        >
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div
                                                        style="min-height:10px;font-size:10px;line-height:10px"
                                                        >&nbsp;</div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td
                                    width="1%"
                                    >
                                    <table
                                        width="20"
                                        cellspacing="0"
                                        cellpadding="0"
                                        border="0"
                                        >
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div
                                                        style="min-height:0px;font-size:0px;line-height:0px"
                                                        >&nbsp;</div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td
                                    align="left"
                                    width="98%"
                                    valign="top"
                                    >
                                    <table
                                        width="1"
                                        cellspacing="0"
                                        cellpadding="0"
                                        border="0"
                                        >
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div
                                                        style="min-height:10px;font-size:10px;line-height:10px"
                                                        >&nbsp;</div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <table
                                        width="98%"
                                        cellspacing="0"
                                        cellpadding="0"
                                        border="0"
                                        style="font-family:Helvetica,‘Helvetica Neue’,Arial,sans-serif"
                                        >
                                        <tbody>
                                            <tr>
                                                <td width="52" style="width:52px">
                                                    <a
                                                        href="{{klikasiUrl}}/{{userUrlProfile}}"
                                                        title="{{CompletName}}"
                                                        >
                                                        <img
                                                            src="{{klikasiUrl}}/{{userUrlAvatar}}"
                                                            width="38"
                                                            height="38"
                                                            style="background:#999999;border:1px solid #cccccc;padding:1px;vertical-align:middle"
                                                            alt="{{CompletName}}"
                                                            />
                                                        </a>
                                                </td>
                                                <td
                                                    align="left"
                                                    style="color:#000000;font-family:Helvetica,‘Helvetica Neue’,Arial,sans-serif;font-size:14px"
                                                    >
                                                    <p style="margin:0 0 5px">Kaixo {{CompletName}}, jakinarazpen berriak dituzu.</p>
                                                    <p style="margin:0;color:#999999;font-size:11px">
                                                        <img
                                                            src="{{klikasiUrl}}/img/fontawesome-png/grey/16/calendar.png"
                                                            height="12"
                                                            width="12"
                                                            style="vertical-align:middle"
                                                            />{{currentDate}}</p>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <table
                                        width="1"
                                        cellspacing="0"
                                        cellpadding="0"
                                        border="0"
                                        >
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div style="min-height:20px;font-size:20px;line-height:20px">&nbsp;</div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <table width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#FFFFFF" style="font-family:Helvetica,‘Helvetica Neue’,Arial,sans-serif;margin:0 0 10px">
                                        <tbody>
                                            <tr colspan="3">
                                                <td>
                                                    <table
                                                        border="0"
                                                        cellspacing="0"
                                                        cellpadding="0"
                                                        style="margin:0 0 10px;text-align:left"
                                                        >
                                                        <tbody>
                                                            <tr>
                                                                <td
                                                                    align="left"
                                                                    style="padding-right:10px"
                                                                    >
                                                                    <img
                                                                        src="{{klikasiUrl}}/img/fontawesome-png/white/32/heart-o.png"
                                                                        border="0"
                                                                        style="background:#999999;margin:0"
                                                                        height="30"
                                                                        width="30"
                                                                        />
                                                                </td>
                                                                <td align="left">
                                                                    <p style="margin:0;color:#999999;display:block;font-size:11px;font-weight:400">
                                                                        <a
                                                                            href="{{klikasiUrl}}/jakinarazpenak/index/mota/atsegin-dut/"
                                                                            title="Atsegin Dut"
                                                                            style="text-decoration: none !important; color: #999;"
                                                                            >Atsegin Dut</a>
                                                                    </p>
                                                                    <p style="margin:0;display:block">
                                                                        {{#atseginDut}}
                                                                            <span style="color:#00aa00;font-size:18px;font-weight:700"><span style="font-size:13px">+</span>{{atseginDut}}</span>
                                                                        {{/atseginDut}}

                                                                        {{^atseginDut}}
                                                                            <span style="color:#000000;font-size:18px;font-weight:700"><span style="font-size:13px"></span>{{atseginDut}}</span>
                                                                        {{/atseginDut}}
                                                                    </p>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    <table
                                                        border="0"
                                                        cellspacing="0"
                                                        cellpadding="0"
                                                        style="margin:0 0 10px;text-align:left"
                                                        >
                                                        <tbody>
                                                            <tr>
                                                                <td
                                                                    align="left"
                                                                    style="padding-right:10px"
                                                                    >
                                                                    <img
                                                                        src="{{klikasiUrl}}/img/fontawesome-png/white/32/comments.png"
                                                                        border="0"
                                                                        style="background:#999999;margin:0"
                                                                        height="30"
                                                                        width="30"
                                                                        />
                                                                </td>
                                                                <td align="left">
                                                                    <p style="margin:0;color:#999999;display:block;font-size:11px;font-weight:400">
                                                                        <a
                                                                            href="{{klikasiUrl}}/jakinarazpenak/index/mota/iruzkin-berria/"
                                                                            title="Iruzkin Berria"
                                                                            style="text-decoration: none !important; color: #999;"
                                                                            >Iruzkin Berria</a>
                                                                    </p>
                                                                    <p style="margin:0;display:block">
                                                                        {{#iruzkinBerria}}
                                                                            <span style="color:#00aa00;font-size:18px;font-weight:700"><span style="font-size:13px">+</span>{{iruzkinBerria}}</span>
                                                                        {{/iruzkinBerria}}

                                                                        {{^iruzkinBerria}}
                                                                            <span style="color:#000000;font-size:18px;font-weight:700"><span style="font-size:13px"></span>{{iruzkinBerria}}</span>
                                                                        {{/iruzkinBerria}}
                                                                    </p>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    <table
                                                        border="0"
                                                        cellspacing="0"
                                                        cellpadding="0"
                                                        style="margin:0 0 10px;text-align:left"
                                                        >
                                                        <tbody>
                                                            <tr>
                                                                <td
                                                                    align="left"
                                                                    style="padding-right:10px"
                                                                    >
                                                                    <img
                                                                        src="{{klikasiUrl}}/img/fontawesome-png/white/32/star.png"
                                                                        border="0"
                                                                        style="background:#999999;margin:0"
                                                                        height="30"
                                                                        width="30"
                                                                        />
                                                                </td>
                                                                <td align="left">
                                                                    <p style="margin:0;color:#999999;display:block;font-size:11px;font-weight:400">
                                                                        <a
                                                                            href="{{klikasiUrl}}/jakinarazpenak/index/mota/gustoko-berria/"
                                                                            title="Gustoko Berria"
                                                                            style="text-decoration: none !important; color: #999;"
                                                                            >Gustoko Berria</a>
                                                                    </p>
                                                                    <p style="margin:0;display:block">
                                                                        {{#gustokoBerria}}
                                                                            <span style="color:#00aa00;font-size:18px;font-weight:700"><span style="font-size:13px">+</span>{{gustokoBerria}}</span>
                                                                        {{/gustokoBerria}}

                                                                        {{^gustokoBerria}}
                                                                            <span style="color:#000000;font-size:18px;font-weight:700"><span style="font-size:13px"></span>{{gustokoBerria}}</span>
                                                                        {{/gustokoBerria}}
                                                                    </p>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr colspan="3">
                                                <td>
                                                    <table
                                                        border="0"
                                                        cellspacing="0"
                                                        cellpadding="0"
                                                        style="margin:0 0 10px;text-align:left"
                                                        >
                                                        <tbody>
                                                            <tr>
                                                                <td
                                                                    align="left"
                                                                    style="padding-right:10px"
                                                                    >
                                                                    <img
                                                                        src="{{klikasiUrl}}/img/fontawesome-png/white/32/users.png"
                                                                        border="0"
                                                                        style="background:#999999;margin:0"
                                                                        height="30"
                                                                        width="30"
                                                                        />
                                                                </td>
                                                                <td align="left">
                                                                    <p style="margin:0;color:#999999;display:block;font-size:11px;font-weight:400">
                                                                        <a
                                                                            href="{{klikasiUrl}}/jakinarazpenak/index/mota/kolaborazio-eskaera/"
                                                                            title="Kolaborazio Eskaera"
                                                                            style="text-decoration: none !important; color: #999;"
                                                                            >Kolaborazio Eskaera</a>
                                                                    </p>
                                                                    <p style="margin:0;display:block">
                                                                        {{#kolaborazioEskaera}}
                                                                            <span style="color:#00aa00;font-size:18px;font-weight:700"><span style="font-size:13px">+</span>{{kolaborazioEskaera}}</span>
                                                                        {{/kolaborazioEskaera}}

                                                                        {{^kolaborazioEskaera}}
                                                                            <span style="color:#000000;font-size:18px;font-weight:700"><span style="font-size:13px"></span>{{kolaborazioEskaera}}</span>
                                                                        {{/kolaborazioEskaera}}
                                                                    </p>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    <table
                                                        border="0"
                                                        cellspacing="0"
                                                        cellpadding="0"
                                                        style="margin:0 0 10px;text-align:left"
                                                        >
                                                        <tbody>
                                                            <tr>
                                                                <td
                                                                    align="left"
                                                                    style="padding-right:10px"
                                                                    >
                                                                    <img
                                                                        src="{{klikasiUrl}}/img/fontawesome-png/white/32/institution.png"
                                                                        border="0"
                                                                        style="background:#999999;margin:0"
                                                                        height="30"
                                                                        width="30"
                                                                        />
                                                                </td>
                                                                <td align="left">
                                                                    <p style="margin:0;color:#999999;display:block;font-size:11px;font-weight:400">
                                                                        <a
                                                                            href="{{klikasiUrl}}/jakinarazpenak/index/mota/irakasle-eskaera/"
                                                                            title="Irakasle Eskaera"
                                                                            style="text-decoration: none !important; color: #999;"
                                                                            >Irakasle Eskaera</a>
                                                                    </p>
                                                                    <p style="margin:0;display:block">
                                                                        {{#irakasleEskaera}}
                                                                            <span style="color:#00aa00;font-size:18px;font-weight:700"><span style="font-size:13px">+</span>{{irakasleEskaera}}</span>
                                                                        {{/irakasleEskaera}}

                                                                        {{^irakasleEskaera}}
                                                                            <span style="color:#000000;font-size:18px;font-weight:700"><span style="font-size:13px"></span>{{irakasleEskaera}}</span>
                                                                        {{/irakasleEskaera}}
                                                                    </p>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                               </td>
                                               <td>
                                               </td>
                                               <td>
                                               </td>
                                               <td>
                                               </td>
                                           </tr>

                                        </tbody>
                                    </table>

                            <table
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                bgcolor="#333"
                                style="background:#cccccc"
                                >
                                <tbody>
                                    <tr>
                                        <td
                                            align="left"
                                            width="98%"
                                            valign="top"
                                            >
                                            <table
                                                width="1"
                                                cellspacing="0"
                                                cellpadding="0"
                                                border="0"
                                                >
                                                <tbody>
                                                    <tr>
                                                        <td>
                                                            <div style="min-height:1px;font-size:1px;line-height:1px">&nbsp;</div>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>

            </td>
        </tr>
    </tbody>
</table>