<div class="modal" id="sartuDialog">
**********************************
    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">
                    <h3><img
                            src="images/logo_footer_klikasi.png"
                            alt="Klikasi. Sortu. Partekatu. Ikasi."
                            />Saioa hasi</h3>
            </div>

            <div class="modal-body">

                <form
                    class="form-horizontal"
                    role="form"
                    method="POST"
                    id="sartuFormDialog"
                    data-url="sartu/sartu-dialog/?format=json"
                    autocomplete="off"
                    >

                    <div class="form-group">

                        <div class="col-sm-12">
                            <input
                                type="text"
                                name="erabiltzailea"
                                id="inputEmail3"
                                class="form-control"
                                placeholder="Erabiltzailea"
                                required="required"
                                />
                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-sm-12">
                            <input
                                type="password"
                                name="pasahitza"
                                id="pasahitza"
                                class="form-control"
                                placeholder="Pasahitza"
                                required="required"
                                />
                        </div>

                    </div>

                    <div class="messageWarningForm hide">
                        <span class="msg error"></span>
                    </div>

                    <div class="form-group">

                        <div class="col-sm-4  col-sm-offset-5">

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="gogoratu" value="true" /> Gogoratu
                                </label>
                            </div>

                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-sm-12 text-center">
                            <button type="submit" class="btn btn-default" id="bidali">Bidali</button>
                            <button type="button" class="btn btn-default" id="close">Utzi</button>
                        </div>
                    </div>

                    <div class="sartuLoading"></div>

                </form>

            </div>

            <div class="modal-footer">

                <a
                    href="?izena-eman=true"
                    title="Izena Eman"
                    class="pull-left"
                    >Izena Eman</a>

                <a
                    href="pasahitza-berreskuratu/"
                    title="Pasahitza Berreskuratu"
                    class="pull-right"
                    >Pasahitza Berreskuratu</a>
            </div>

        </div>

    </div>

</div>